== Asciidoc cheatsheet for GitHub

This is a simple cheat sheet for editors of the Great COw BASIC Help source files.

== GitHub limitations

This cheatsheet contains small part of Asciidoc markup which works and
looks fine on GitHub. There is also link:full.adoc[full cheatsheet], but
for now it's main use is to show bugs, design issues, GitHub limitations
and other differences from http://powerman.name/doc/asciidoc[how Asciidoc
cheatsheet should really looks like].

== Great Cow BASIC Help

The format is pre-determined.  Meaning the layout and the style sheets are already set.&#160;&#160;These notes are to enable the casual editor insights into some of the tricks when editing Asciidoc's.  

To add an example hard space, use the following:

.An example hard break
----
&#160;&#160;
----
{empty} +
To add a table, using the following:

.An example table
----
[options="header,footer"]
|=======================
|Col 1|Col 2      |Col 3
|1    |Item 1     |a
|2    |Item 2     |b
|3    |Item 3     |c
|6    |Three items|d
|=======================
----
{empty} +
To add an empty line, use the following:

.An example empty line
----
{empty} +
----



++++
