== Asciidoc cheatsheet for GitHub


=== Introduction

These are the pages and the toolchain used to generate the Great Cow BASIC Help system.

The source files, in ADOC format, are here: https://github.com/Anobium/Great-Cow-BASIC-Help/tree/master/source

For the online operation Help, see here: http://gcbasic.sourceforge.net/help

For the daily build, see here: http://gcbasic.sourceforge.net/help/output/



This is a simple cheat sheet for editors of the Great Cow BASIC Help source files.

=== GitHub limitations

This cheatsheet contains small part of Asciidoc markup which works and
looks fine on GitHub.&#160;&#160;There is also link:https://github.com/powerman/asciidoc-cheatsheet/blob/master/README.adoc[full cheatsheet], but
for now its main use is to show bugs, design issues, GitHub limitations
and other differences from http://powerman.name/doc/asciidoc[how Asciidoc
cheatsheet should really looks like].

=== Great Cow BASIC Help

The format is pre-determined.&#160;&#160;Meaning the layout and the style sheets are already mandated, please refer to existing Help pages as a reference.&#160;&#160;These notes are to enable the casual editor insights into some of the tricks when editing Asciidoc's.

To add an example hard space, use the following:

=== Cheat Sheet

This is an example of how to show user code.  Four dashes, then code indented by two tabs, terminated by four dashes.

.An example of showing  user code
----
    ----

    GLCDCLS

    ----
----
{empty} +


This is how to added a hard space. Always add a hard speace at the end of each sentence in a paragraph.

.An example hard space
----
&#160;&#160;
----
{empty} +
To add a table, using the following:

.An example table
----
[cols="3,4,4", options="header,autowidth"]
|===
|Constant
|Purpose
|Default

|`GLCD_WIDTH`
|The width parameter of the GLCD
|Set automatically

|`GLCD_HEIGHT`
|The height parameter of the GLCD
|Set automatically

|`GLCDFontWidth`
|Specifies the font width of the Great Cow BASIC font set.
|6
|===

----

Will dispay as:

[cols="3,4,4", options="header,autowidth"]
|===
|Constant
|Purpose
|Default

|`GLCD_WIDTH`
|The width parameter of the GLCD
|Set automatically

|`GLCD_HEIGHT`
|The height parameter of the GLCD
|Set automatically

|`GLCDFontWidth`
|Specifies the font width of the Great Cow BASIC font set.
|6
|===
{empty} +
{empty} +
To add an empty line, use the following:

.An example empty line
----
{empty} +
----



++++
