==== HPWM Fixed Mode

*Syntax:*
[subs="specialcharacters,quotes"]
----
    PWMOn

    'or

    PWMOff

----
*Command Availability:*

*Only* available on Microchip PIC microcontrollers with a CCP1 module.

See here <<_hpwm_ccp,HPWM CCP>> for the method to change PWM parameters dynamically or to use other CCP channels - this method is fixed to CCP1.

*Explanation:*

This command sets up the hardware PWM module of the Microchip PIC microcontroller to generate
a PWM waveform of the given frequency and duty cycle. Once this command
is called, the PWM will be emitted until PWMOff is called.


These constants are required for PWMOn.

[cols=3, options="header,autowidth"]
|===
|*Constant Name*
|*Controls*
|*Default Value*

|`PWM_Freq`
|Specifies the output frequency of the PWM module in KHz.
|38

|`PWM_Duty`
|Sets the duty cycle of the PWM module output. Given as percentage.
|50
|===

HPWM and PWMOff do not require any constants to operate.

Optimisation of the hardware PWM code can be implemented within Great Cow BASIC, see <<_hardware_pwm_code_optimisation, Hardware PWM Code Optimisation>>


*_Software PWM_*
[cols=3, options="header,autowidth"]
[subs="specialcharacters,quotes"]
|===
|*Constant Name*
|*Controls*
|*Default Value*

|`PWM_Delay`
|The PWM Period. The length of any delay used will be multiplied by 255.
If no value is specified, no delays will be inserted into the PWM
routine.
|Not defined - no delay

|`PWM_Out _n_`
|The port physical port on the Microchip PIC microcontroller that corresponds to channel _n_. +
_n_ can represent 1, 2, 3 or 4.
|Not Defined
|===


*Example 1:*
----
    'This program will set the brightness of an LED.

    'Select chip model and speed
    #chip 16F18855, 32

    'Generated by PIC PPS Tool for Great Cow Basic
    '
    'Template comment at the start of the config file
    '
    #startup InitPPS, 85

    Sub InitPPS

            'Module: CCP1
            RA2PPS = 0x000C    'CCP1 > RA2
            CCP1PPS = 0x0002    'RA2 > CCP1 (bi-directional)

    End Sub
    'Template comment at the end of the config file


    'Set the PWM pin to output mode
    DIR PORTA.2 out

    'Main code
    do
        'Turn up brightness over the range
        For Bright = 1 to 255
            HPWM 6, 40, Bright, 2
            wait 10 ms
        next
        'Turn down brightness over the range
        For Bright = 255 to 1
            HPWM 6, 40, Bright, 2
            wait 10 ms
        next
    loop
----

*Example 2:*
----
    #chip 16f877a,20

    'Set the PWM pin to output mode
    DIR PORTC.2 out

    'Main code

    #define PWM_Freq 38      'Frequency of PWM in KHz
    #define PWM_Duty 50      'Duty cycle of PWM (%)

    PWMOn

    wait 10 s                'Wait 10 s

    PWMOff

    do
    loop

----


*For more help, see* <<_pwmon,PWMOn>> and <<_pwmoff,PWMOff>>
