==== InitSer

*Syntax:*
[subs="specialcharacters,quotes"]
----
	`InitSer` _channel, rate, start, data, stop, parity, invert_
----
*Command Availability:*

Available on all microcontrollers.

*Explanation:*

This command will set up the serial communications. The parameters are
as follows:

`_channel_` is 1, 2 or 3, and refers to the I/O ports that are used for
communication.

`_rate_` is the bit rate, which is given by the letter r and then the
desiredrate in bps. Acceptable units are r300, r600, r1200, r2400,
r4800, r9600 and r19200.

`_start_` gives the number of start bits, which is usually 1. To make
the microcontroller wait for the start bit before proceeding with the receive, add
128 to `_start_`. (Note: it may be desirable to use the `WaitForStart`
constant here.)

`_data_` tells the program how many data bits are to be sent or received.
In most situations t his is 8, but it can range between 1 and 8,
inclusive.

`_stop_` is the number of stop bits. If _start_ bit 7 is on, then this
number will be ignored.

`_parity_` refers to a system of error checking used by many devices. It
can be odd (in which there must always be an odd number of high bits),
even (where the number of high bits must always be even), or none (for
systems that do not use parity).

`_invert_` can be either "normal" or "invert". If it in "invert", then
high bits will be changed to low, and low to high.

*Example:*

Please refer to <<_sersend,SerSend>> for an example of `InitSer`

*For more help, see* <<_rs232_software_overview,RS232 Software Overview>>