==== Interrupts overview

*Introduction*

Interrupts are a feature of many microcontrollers. They allow the
microcontroller to temporarily pause (interrupt) the code it is running
and then start running another piece of code when some event occurs.
Once it has dealt with the event, it will return to where it was and
continue running the program.

Many events can trigger an interrupt, such as a timer reaching its
limit, a serial message being received, or a special pin on the
microcontroller receiving a signal.

*Using Interrupts*

There are two ways to use interrupts in Great Cow BASIC. The first way is to use
the On Interrupt command. This will automatically enable a given
interrupt, and run a particular subroutine when the interrupt occurs.

The other way to deal with interrupts is to create a subroutine called
Interrupt. Great Cow BASIC will call this subroutine whenever an interrupt
occurs, and then your code can check the "flag" bits to determine which
interrupt has occured, and what should be done about it. If you use this
approach, then you'll need to enable the desired interrupts manually. It
is also essential that your code clears the flag bits, or else the
interrupt routine will be called repeatedly.

Some combination of these two methods is also possible - the code
generated by On Interrupt with check to see if the interrupt is one it
recognises. If the interrupt is recognised, On Interrupt will deal with
it - if not, the Interrupt subroutine will be called to deal with the
interrupt.

The recommended way is to use On Interrupt, as it is both more efficient
and easier to set up.

During some sections of code, it is desirable not to have any interrupts
occur. If this is the case, then use the IntOff command to disable
interrupts at the start of the section, and IntOn to re-enable them at
the end. If any interrupt events occur while interrupts are disabled,
then they will be processed as soon as interrupts are re-enabled. If the
program does not use interrupts, IntOn and IntOff will be removed
automatically by Great Cow BASIC.

*See Also* <<_intoff,IntOff>>, <<_inton,IntOn>>,
<<_on_interrupt,On Interrupt>>