===== LCD_IO 2

*Using connection mode 2:*

This method uses a Data and a Clock line via a shift register to control the LCD display.
This method is used when the LCD is connected through a shift register IC either using a 74HC164 or a 74LS174, as detailed at http://gcbasic.sourceforge.net/library/DIAGRAMS/2-Wire%20LCD/[here].
This connection method is also called a 2-wire connection.


This is a *deprecated* method mode to connect an LCD display to a microcontroller via a shift registry either a 74LS174 (or a 74LS164 with diode connected to pin 11).   This method does not support backlight control and has no additional input/output pin.

If you have used the 2-wire mode prior to August 2015, please choose this method for your existing code.

See <<_lcd_io_2_74xx164,LCD_IO 2 74xx164>> for the preferred method to connect an LCD display to a microcomputer via a shift register.

*Relevant Constants:*

Specific constants are used to control settings for the Liquid Crystal Display routines included with Great Cow BASIC. To set these constants the main program should specific constants to support the connection mode using #define.
When using 2-bit mode only three constants must be set - all others are optional or can be ignored.


[cols=3, options="header,autowidth"]
|===
|*Constant Name*
|*Controls*
|*Default Value*

|`LCD_IO`
|The I/O mode.
|`2`

|`LCD_DB`
|The data pin used in 2-bit mode.
|*Mandated*

|`LCD_CB`
|The clock pin used in 2- bit mode.
|*Mandated*
|===

For a code example download http://gcbasic.sourceforge.net/library/DEMO%20CODE/Demo%20code%20for%20lcd/[Two Wire LCD Example].


See for further code examples see http://sourceforge.net/projects/gcbasic/files/Demonstration%20Files/LCD%20Solutions/[Two Wire LCD Solutions].



See the separate sections of the Help file for the specifics of each
Connection Mode.

*For more help, see*
<<_lcd_io_0,LCD_IO 0>>, <<_lcd_io_1,LCD_IO 1>>,
<<_lcd_io_2_74xx164,LCD_IO 2_74xx164>>, <<_lcd_io_2_74xx174,LCD_IO 2_74xx174>>,
<<_lcd_io_4,LCD_IO 4>>, <<_lcd_io_8,LCD_IO 8>>,
<<_lcd_io_10,LCD_IO 10>> or <<_lcd_io_12,LCD_IO 12>>