===== LCD_IO 0

*Using connection mode 0:*

To use connection mode 0, a subroutine to write a byte to the LCD *must* be provided.

Optionally, another subroutine to read a byte from the LCD can also be
defined.  If the LCD was to be read, the function `LCDReadByte` would be set to the name of a function that reads the LCD and returns the data byte from the LCD.
If there is no way (or no requirement) to read from the LCD, then the `LCD_NO_RW` constant must be set.

In connection mode 0, the `LCD_RS` constant will be set automatically to an unused bit variable.
The higher level LCD commands (such as `Print` and `Locate`) will set it, and the subroutine is responsible for writing to the LCD.
The subroutine should handle the process and then set the RS pin on the LCD appropriately.

*Relevant Constants:*

Specific constants are used to control settings for the Liquid Crystal Display routines included with Great Cow BASIC.  To set these constants the main program should specific constants to support the connection mode using #define.

When using connection mode 0 only one constant must be set - all others are optional or can be ignored.

[cols=3, options="header,autowidth"]
|===
|*Constant Name*
|*Controls*
|*Value*

|`LCD_IO`
|The I/O mode.
|`0`

|===

For a code example of connection mode 0 program, download http://gcbasic.sourceforge.net/library/DEMO%20CODE/Demo%20code%20for%20lcd/Demo%20mode%200.gcb[here].

See the separate sections of the Help file for the specifics of each
Connection Mode.

*For more help, see*
<<_lcd_io_1,LCD_IO 1>>, <<_lcd_io_2,LCD_IO 2>>,
<<_lcd_io_2_74xx164,LCD_IO 2_74xx164>>, <<_lcd_io_2_74xx174,LCD_IO 2_74xx174>>,
<<_lcd_io_4,LCD_IO 4>>,<<_lcd_io_8,LCD_IO 8>>,
<<_lcd_io_10,LCD_IO 10>> or <<_lcd_io_12,LCD_IO 12>>