==== ST7735 Controllers

This section covers GLCD devices that use the ST7735 graphics controller.  The ST7735 is a single-chip controller/driver for 262K-color, graphic type TFT-LCD.

The Great Cow BASIC constants shown below control the configuration of the ILI9340 controller. &#160;&#160;&#160;Great Cow BASIC supports an 8 bit bus connectivity. The 8 bit must be a single port of consective bits  - this is shown in the tables below.

To use the ST7735 driver simply include the following in your user code.  This will initialise the driver.

----
    #include <glcd.h>
    #DEFINE GLCD_TYPE GLCD_TYPE_ST7735

    'Pin mappings for ST7735
    #define GLCD_DC     porta.0           'example port setting
    #define GLCD_CS     porta.1           'example port setting
    #define GLCD_RESET  porta.2           'example port setting
    #define GLCD_DI     porta.3           'example port setting
    #define GLCD_DO     porta.4           'example port setting
    #define GLCD_SCK    porta.5           'example port setting

----

The Great Cow BASIC constants for control display characteristics are shown in the table below.


[cols=3, options="header,autowidth"]
|===
|*Constants*
|*Controls*
|*Options*

|`GLCD_TYPE`
|`GLCD_TYPE_ST7735`
|

|`GLCD_DATA_PORT`
|Not Available for this controller.
|Not applicable.

|`GLCD_DC`
|Specifies the output pin that is connected to Data/Command IO pin on the
GLCD.
|Required

|`GLCD_CS`
|Specifies the output pin that is connected to Chip Select (CS) on the
GLCD.
|Required

|`GLCD_Reset`
|Specifies the output pin that is connected to Reset pin on the GLCD.
|Required

|`GLCD_DI`
|Specifies the output pin that is connected to Data In (GLCD out) pin on
the GLCD.
|Required

|`GLCD_D0`
|Specifies the output pin that is connected to Data Out (GLCD in) pin on
the GLCD.
|Required

|`GLCD_SLK`
|Specifies the output pin that is connected to Clock (CLK) pin on the
GLCD.
|Required
|===

The Great Cow BASIC constants for control display characteristics are shown in the table below. +


[cols="1,1,^1", options="header,autowidth"]
|===
|*Constants*
|*Controls*
|*Default*

|`GLCD_WIDTH`
|The width parameter of the GLCD
|`160` +
This cannot be changed

|`GLCD_HEIGHT`
|The height parameter of the GLCD
|`128` +
This cannot be changed

|`GLCDFontWidth`
|Specifies the font width of the Great Cow BASIC font set.
|`6`
|===


The Great Cow BASIC commands supported for this GLCD are shown in the table below.&#160;&#160;&#160;Always review the appropiate library for the latest full set of supported commands.



[cols=3, options="header,autowidth"]
|===
|*Command*
|*Purpose*
|*Example*

|`GLCDCLS`
|Clear screen of GLCD
|`GLCDCLS`

|`GLCDPrint`
|Print string of characters on GLCD using GCB font set
|`GLCDPrint( Xposition, Yposition, Stringvariable )`

|`GLCDDrawChar`
|Print character on GLCD using GCB font set
|`GLCDDrawChar( Xposition, Yposition, CharCode )`

|`GLCDDrawString`
|Print characters on GLCD using GCB font set
|`GLCDDrawString( Xposition, Yposition, Stringvariable )`

|`Box`
|Draw a box on the GLCD to a specific size
|`Box ( Xposition1, Yposition1, Xposition2, Yposition2, [Optional In
LineColour as 0 or 1] )`

|`FilledBox`
|Draw a box on the GLCD to a specific size that is filled with the
foreground colour.
|`FilledBox (Xposition1, Yposition1, Xposition2, Yposition2, [Optional In
LineColour 0 or 1] )`

|`Line`
|Draw a line on the GLCD to a specific length that is filled with the
specific attribute.
|`Line ( Xposition1, Yposition1, Xposition2, Yposition2, [Optional In
LineColour 0 or 1] )`

|`PSet`
|Set a pixel on the GLCD at a specific position that is set with the
specific attribute.
|`PSet(Xposition, Yposition, Pixel Colour 0 or 1)`

|`GLCDWriteByte`
|Set a byte value to the controller, see the datasheet for usage.
|`GLCDWriteByte (LCDByte)`

|`GLCDReadByte`
|Read a byte value from the controller, see the datasheet for usage.
|`bytevariable = GLCDReadByte`

|`ST7735_[color]`
|Specify color as a parameter for many GLCD commands
|Color constants for this device are shown in the list below. +


 Any color can be defined using a valid hexidecimal word value between 0x0000 to 0xFFFF.
|===


----
   ST7735_BLACK   'hexidecimal value 0x0000
   ST7735_BLUE    'hexidecimal value 0xF800
   ST7735_RED     'hexidecimal value 0x001F
   ST7735_GREEN   'hexidecimal value 0x07E0
   ST7735_CYAN    'hexidecimal value 0xFFE0
   ST7735_MAGENTA 'hexidecimal value 0xF81F
   ST7735_YELLOW  'hexidecimal value 0x07FF
   ST7735_WHITE   'hexidecimal value 0xFFFF
----

For a ST7735 datasheet, please refer
http://www.crystalfontz.com/controllers/ST7735_V2.1_20100505.pdf[here.]

*Example:*

----
    ;Chip Settings
    #chip 16F1937,32
    #config Osc = INT, VCAPEN_OFF, MCLRE_ON, PLLEN_ON, CLKOUTEN_OFF

    #include <glcd.h>

    'Defines for ST7735
    #define GLCD_TYPE GLCD_TYPE_ST7735
    'Pin mappings for ST7735
    #define GLCD_DC porta.0
    #define GLCD_CS porta.1
    #define GLCD_RESET porta.2
    #define GLCD_DI porta.3
    #define GLCD_DO porta.4
    #define GLCD_SCK porta.5

    GLCDPrint(0, 0, "Test of the ST7735 Device")
    end
----



*For more help, see*
<<_glcdcls,GLCDCLS>>, <<_glcddrawchar,GLCDDrawChar>>, <<_glcdprint,GLCDPrint>>, <<_glcdreadbyte,GLCDReadByte>>, <<_glcdwritebyte,GLCDWriteByte>> or <<_pset,Pset>>

Supported in <GLCD.H>
