== Development Guide

There are lots of ways to contribute to the Great Cow BASIC project: coding, testing, improving the build process and tools, or contributing to the documentation.
This guide provides information that will not only help you get started as a Great Cow BASIC contributor, 
but that you wiil find useful to refer to even if you are already an experienced contributor.

*_Need help?_*

The Great Cow BASIC community prides itself on being an open, accessible, and friendly community for new participants.
If you have any difficulties getting involved or finding answers to your questions, please bring those questions to the forum via the discussion boards, where we can help you get started.

We know even before you start contributing that getting set up to work on Great Cow BASIC and finding a bug that is a good fit for your skills can be a challenge. 
We are always looking for ways to improve this process: making Great Cow BASIC more open, accessible, and easier to participate with. 
If you are having any trouble following this documentation, or hit a barrier you cannot get around, please contact use via the discussion forum.
We will solve hurdles for new contributors and make Great Cow BASIC better.

This section addresses developing libraries but this guide is appropiate to any Great Cow BASIC development.&nbsp;&nbsp;


The section covers Constants, Variables, Script syntax (gotchas) and a recommended programming style.

*CONSTANTS*

A constant is a value that cannot be altered by the program during normal execution.&nbsp;&nbsp;
Within Great Cow BASIC there are two ways to create constants.&nbsp; &nbsp;
1. with the `#DEFINE` instruction, or,
2. via `#SCRIPT .. #ENDSCRIPT'. &nbsp; &nbsp;Within a script constants can be created and changed.  A script is process that is executed  prior to the Great Cow BASIC source program is processing the main user program.

An example of using `#DEFINE` is

----
        #DEFINE TIME_DELAY_VALUE    10
----

The script construct is

----
        #SCRIPT
              'Create a constant
              TIME_REPEAT_VALUE  =  10
        #ENDSCRIPT
----

*_Guide for constants_*

The following rules are recommended.

1.  All CONSTANTS are capitalized
2.  Underscores are permitted in constant names within Scripts **
3.  No prefix is required when a CONSTANT is PUBLIC.  A PUBLIC constant is one that the user sets or the user can use.
4.  Prefix CONSTANTS with SCRIPT_  when the CONSTANT is used outside of the library specific script section AND ARE NOT EXPOSED AS PUBLIC Constants.  
5.  Prefix CONSTANTS with __ (two underscores)  when the CONSTANT is ONLY used inside the library specific script section
6.  For PUBLIC prefix CONSTANTS with the capability name, _ (one underscore)  and then a meaningful title, as follows
            GLCD_HEIGHT
            SPISRAM_TYPE
7.  All scripts within a specific library should be the first major section the library.   Scripts within methods  ( Sub, Functions) should not be used.
8.  All scripts within a specific library should be the first major section the library.   Scripts within methods  ( Sub, Functions) should not be used. 


*_Other naming recommendations_*

9.  Do not use underscores in subroutine, function or variable names

*_Example library_*
       
  ----
          #startup  startupsub
          #DEFINE I2C_ADDRESS_1  0x4E    'Default address if user omits
          #SCRIPT
                'script code
                'script code
                'script code                         
          #ENDSCRIPT
----


*_Usage Example_*

----
     #SCRIPT  'Calculate Delay Time
             __LCD_DELAY  = ( __LCD_TIMEPERIOD - __LCD_DELAYS) - (INT((4/ChipMHZ) * __LCD_INSTRUCTIONS))
            SCRIPT_LCD_POSTWRITEDELAY = __LCD_DELAY  
            SCRIPT_LCD_CHECKBUSYFLAG = TRUE           
     #ENDSCRIPT

     'user code or code outside of script          
     #IF SCRIPT_LCD_CHECKBUSYFLAG = TRUE
           WaitForReady    'Call subroutine to poll busy flag
           set LCD_RW OFF  'Write mode
     #ENDIF
     WAIT SCRIPT_LCDPOSTWRITEDELAY us
 ----
 
*VARIABLES*

[to be done]


*SCRIPT SYNTAX*

Scripting suppport the preprocessing of the program to create specific constants.&nbsp;&nbsp;
Scripting has a basic syntax and this is detailed in the HELP.&nbsp;&nbsp;
However, this guide is intended to provide insights into the gotchas and best practices.

*_Script Insights_*

Scripting handles the creation of specific constants that can be used within the library.&nbsp;&nbsp;
Many libraries have script to create constants to support PWM, Serial, HEFSAF etc.&nbsp;&nbsp;

You can use the limited script language to complete calculations using real numbers but you MUST ensure the resulting constant is an integer value.&nbsp;&nbsp;
Use the IN() method to ensure an integer is assigned.

You can use IF-THEN-ENDIF but if your IF condtional test uses a chip regiseter or a user define constant then you must ensure the register or constant exists.&nbsp;&nbsp;
If you do not check the registrer or constant exists the script will fail to operate as expected.&nbsp;&nbsp;

There is limted syntax checking.  
You must ensure the quality of the script by extensive testing.

int( register +1s)) will not create an error, but, simple give an unexpected result.



*PROGRAMMING STYLES*

Indenting is standardized.
4 spaces not tab are to be used.

As follows where the indents are all four spaces.  

----
sub  ExampleSub (In VariableName)
    select case VariableName
        case 1
            Do This 
        case 2 
            Do That
    end select
end sub 
----

Not like this:

----
SUB  ExampleSub (In VariableName)
        Select Case VariableName
              Case 1
                               Do This 
              Case 2 
                                Do That
         End Select
End SUB 
----

and, not like this

----
Sub  ExampleSub (In VariableName)
Select Case VariableName
Case 1
Do This 
Case 2 
Do That
End Select
End Sub
----


