==== DS18B20

The DS18B20 is a 1-Wire digital temperature sensor from Maxim IC.

The sensor reports degrees C with 9 to 12-bit precision from -55C to 125C (+/- 0.5C).

Each sensor has a unique 64-Bit Serial number etched into it. This allows for a number of sensors to be used on one data bus. This sensor is used in many data-logging and temperature control projects.

Reading the temperature from a DS18B20 takes up to 750ms(max).

To use the DS18B20 driver the following is required to added to the Great Cow BASIC source file.
----
    #include <DS18B20.h>
----
Note the Great Cow BASIC commands do not work with the older DS1820 or DS18S20 as they have a different internal resolution.

These commands are not designed to be used with parasitically powered DS18B20 sensors.

[cols="10%,60%,30%",options="header"]
|===
|Command
|Usage
|Returns

|ReadDigitalTemp
|Returns two global variables.&#160;&#160;As follows:

*`DSint`* the integer value read from the sensors
*`DSdec`* the string value read from the sensors

|Byte variables:
*`DSint`*

String variable: *`DSdec`*

|ReadTemp
|*`ReadTemp`* is a function that returns the raw value of the sensor.

The temperature is read back in whole degree steps, and the sensor operates from -55 to + 125 degrees Celsius.;&#160;&#160Note that bit 7 is 0 for positive temperature values and 1 for negative values (ie negative values will appear as 128 + numeric value).
|Word variable via the ReadTemp() function


|ReadTemp12
|*`ReadTemp`* is a function that returns the raw 12bit value of the sensor.

The temperature is read back as the raw 12 bit data into a word variable (0.0625 degree resolution).;&#160;&#160The user must interpret the data through mathematical manipulation. See the DS18B20 datasheet for more information on the 12 bit temperature/data information construct.
|Word variable via the ReadTemp12() function
|===

{empty} +
{empty} +

*For more help, see*
<<_readdigitaltemp, ReadDigitalTemp>>, <<_readtemp,ReadTemp>> or <<_readtemp12,ReadTemp12>>
