//erv 04110218
==== HEFRead


*Syntax:*
[subs="quotes"]
----
    'as a subroutine
    HEFRead ( location, data )

    'as a function
    data = HEFRead ( location )
----
*Command Availability:*

Available on all PIC micro-controllers with HEFM memory

*Explanation:*
{empty} +
{empty} +
HEFRead is used to read information, byte values, from HEFM, so that it can be accessed for use in a user program.
{empty} +
{empty} +
`location` represents the location or relative address to read.  The location will range from location 0 to HEF_BYTES - 1, or for all practical purposes 0-127 since all PIC Microcontrollers with HEF support 128 bytes of HEF Memory. HEF_BYTES is a Great Cow BASIC constant that represents the number of bytes of HEF Memory.&#160;&#160;&#160;
{empty} +
{empty} +
`data` is the data that is to be read from the HEFM data storage area.&#160;&#160;&#160;
This must be a byte value.
{empty} +
{empty} +
This method reads data from HEFM given the specific relative location.&#160;&#160;&#160;
This method is similar to the EPRead method for EEPROM.
{empty} +
{empty} +
*Example 1:*
----
    '... code preamble to select part
    '... code to setup serial

    'The following example reads the data at HEFM location 34 into the byte variable “byte_value”.
    'HEFM byte information is in HEFM location 34.

     HEFread( 34, byte_value )
----
{empty} +
{empty} +
*Example 2:*
----
    '... code preamble to select part
    '... code to setup serial

    'The following example reads the data at HEFM location 34 into the byte variable “byte_value” using a function.
    'HEFM byte information is in HEFM location 34.
    
     byte_value = HEFread( 34 )
----
{empty} +
{empty} +
*Example 3:*
----

    '... code preamble to select part
    '... code to setup serial

   Dim Rel_Address,DataByte, Index as Byte
   Dim NVM_Address as Long  ' Absolute Address
   Dim  DataWord, as Word
    
   'Write some data to HEFM 
    HEFWrite (0, 34)
    HEfWrite (32, 15)

    HSerPrintCRLF
    HSerPrint "Show HEFM"
    
    'Call the HEFM_Dump subroutine to read and show the data.
    HEFM_Dump
    End

  ; This subroutine displays the High Endurance Flash Memory on a terminal.
  ; Words are in reverse byte order relative to address.
  ; HEF data resides in the low byte of each  14bit program memory word.
  ; The high byte is not HEF and should always read "3F".

  Sub HEFM_Dump

      Dim Blocknum as Byte
      NVM_Address  = HEF_START_ADDR
      BlockNum = 0

      Repeat  HEF_BYTES    '128

         If NVM_Address % HEF_ROWSIZE_BYTES = 0 then
             If BlockNum > 0 then   HSERPRINTCRLF
             HSerprintCRLF
             HserPrint "Block"
             HSerprint BlockNum
             HSerprint "     0     1     2     3     4     5     6     7"
             BlockNum++
         End if

         If NVM_Address  % 8 = 0 then
             HSerPrintCRLF
             hserprint hex(NVM_Address_H)
             hserprint hex(NVM_ADDRESS)
             hserprint "     "
         End if

         Rel_Address = (NVM_ADDRESS - HEF_START_ADDR)
         HEFRead(Rel_Address, DataWord)

         hserprint hex(DataWord_H)
         hserprint hex(DataWord)
         hserprint "  "

         NVM_Address++ 
    End Repeat
    HserPrintCRLF
End sub
----
{empty} +
{empty} +
If example 3 were displayed on a serial terminal.&#160;&#160;&#160;The result would show:
{empty} +
----
Show HEFM
   
Block0     0     1     2     3     4     5     6     7
3F80     3F22  3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  
3F88     3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  
3F90     3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  
3F98     3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  

Block1     0     1     2     3     4     5     6     7
3FA0     3F0F  3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  
3FA8     3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  
3FB0     3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  
3FB8     3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  

Block2     0     1     2     3     4     5     6     7
3FC0     3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  
3FC8     3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  
3FD0     3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  
3FD8     3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  

Block3     0     1     2     3     4     5     6     7
3FE0     3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  
3FE8     3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  
3FF0     3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  
3FF8     3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  

----
{empty} +
{empty} +
See also
<<_hefm_overview,HEFM Overview>>,
<<_hefread,HEFRead>>,
<<_hefreadword,HEFReadWord>>,
<<_hefwrite,HEFWrite>>,
<<_hefwriteword,HEFWriteWord>>,
<<_hefreadblock,HEFReadBlock>>,
<<_hefwriteblock,HEFWriteBlock>>,
<<_heferaseblock,HEFEraseBlock>>
