==== HEFWriteBlock


*Syntax:*
[subs="quotes"]
----
    HEFWriteBlock ( block_number,  buffer(), [, NumberOfBytes] )
----
*Command Availability:*

Available on all PIC micro-controllers with HEFM memory.

*Explanation:*
{empty} +
{empty} +
HEFWriteBlock is used to write information from a user buffer to HEFM.&#160;&#160;&#160;
Once the block is written  it can be accessed for use within a user program.
{empty} +
{empty} +
The parameters are as follows:
{empty} +
`block_number` represents the block to be written to.&#160;&#160;&#160;
The block_number parameter is used to calculate the physical memory location(s) that are updated.
{empty} +
`buffer()` represents any valid array or string.&#160;&#160;&#160;
The `buffer()` will be used as the data source that is written to the HEFM block .&#160;&#160;&#160;
The  `buffer()`, an array or string, is handled as a buffer of bytes values.&#160;&#160;&#160;
The `buffer()` should be the same size as a row/block of HEFM.  For most PIC Microcontrollers this will be 32 bytes. For PIC microcontrollers with 2KW or less of Program Memory this will be 16 Bytes. Best practice is to size the buffer using the HEF_ROWSIZE_BYTES constant. If the size of the `buffer()` exceeds the device specific HEF_ROWSIZE_BYTES, the excess data will not be handled and the buffer will be truncated at the HEF_ROWSIZE_BYTES limit.&#160;&#160;&#160;
{empty} +
NumberOfBytes`, an optional parameter, is used to specify numeber of bytes to write, starting at the first location in the HEFM block. &#160;&#160;&#160;
This parameter  is not normally required as the default is set to the Great Cow BASIC constant `HEF_ROWSIZE_BYTES`.
{empty} +
{empty} +

*Example 1:*
----
    '... code preamble to select part
    '... code to setup serial

    HSerPrintStringCRLF "HEFMWriteBlock - write string to Block 2"

    Dim HelloWorld as String
    HelloWorld="Hello GCB World!"

    'HEFwriteBlock operation!!
    HEFwriteBlock( 2 , HelloWorld , len(HelloWorld) )       'Hello string copied to row 2

    'A utility method to show the contents of the HEFM.  See HEFMRead()
    HEFM_Dump

----

{empty} +
{empty} +
If example 1 where displayed on a serial terminal.&#160;&#160;&#160;
The result would show. Note the value display at the start of block 2 @ 0x3F80.
----


    HEFMWriteBlock - write string to Block 2

            0     1     2     3     4     5     6     7
    3F00  00FF  00FF  00FF  00FF  00FF  00FF  00FF  00FF
    3F08  00FF  00FF  00FF  00FF  00FF  00FF  00FF  00FF
    3F10  00FF  00FF  00FF  00FF  00FF  00FF  00FF  00FF
    3F18  00FF  00FF  00FF  00FF  00FF  00FF  00FF  00FF
    3F20  00FF  00FF  00FF  00FF  00FF  00FF  00FF  00FF
    3F28  00FF  00FF  00FF  00FF  00FF  00FF  00FF  00FF
    3F30  00FF  00FF  00FF  00FF  00FF  00FF  00FF  00FF
    3F38  00FF  00FF  00FF  00FF  00FF  00FF  00FF  00FF
            0     1     2     3     4     5     6     7
    3F40  00FF  00FF  00FF  00FF  00FF  00FF  00FF  00FF
    3F48  00FF  00FF  00FF  00FF  00FF  00FF  00FF  00FF
    3F50  00FF  00FF  00FF  00FF  00FF  00FF  00FF  00FF
    3F58  00FF  00FF  00FF  00FF  00FF  00FF  00FF  00FF
    3F60  00FF  00FF  00FF  00FF  00FF  00FF  00FF  00FF
    3F68  00FF  00FF  00FF  00FF  00FF  00FF  00FF  00FF
    3F70  00FF  00FF  00FF  00FF  00FF  00FF  00FF  00FF
    3F78  00FF  00FF  00FF  00FF  00FF  00FF  00FF  00FF
            0     1     2     3     4     5     6     7
    3F80  0048  0065  006C  006C  006F  0020  0047  0043
    3F88  0042  0020  0057  006F  0072  006C  0064  0021
    3F90  00FF  00FF  00FF  00FF  00FF  00FF  00FF  00FF
    3F98  00FF  00FF  00FF  00FF  00FF  00FF  00FF  00FF
    3FA0  00FF  00FF  00FF  00FF  00FF  00FF  00FF  00FF
    3FA8  00FF  00FF  00FF  00FF  00FF  00FF  00FF  00FF
    3FB0  00FF  00FF  00FF  00FF  00FF  00FF  00FF  00FF
    3FB8  00FF  00FF  00FF  00FF  00FF  00FF  00FF  00FF
            0     1     2     3     4     5     6     7
    3FC0  00FF  00FF  00FF  00FF  00FF  00FF  00FF  00FF
    3FC8  00FF  00FF  00FF  00FF  00FF  00FF  00FF  00FF
    3FD0  00FF  00FF  00FF  00FF  00FF  00FF  00FF  00FF
    3FD8  00FF  00FF  00FF  00FF  00FF  00FF  00FF  00FF
    3FE0  00FF  00FF  00FF  00FF  00FF  00FF  00FF  00FF
    3FE8  00FF  00FF  00FF  00FF  00FF  00FF  00FF  00FF
    3FF0  00FF  00FF  00FF  00FF  00FF  00FF  00FF  00FF
    3FF8  00FF  00FF  00FF  00FF  00FF  00FF  00FF  00FF

----
{empty} +
{empty} +
See also
<<_hefm_overview,HEFM Overview>>,
<<_hefread,HEFRead>>,
<<_hefreadword,HEFReadWord>>,
<<_hefwrite,HEFWrite>>,
<<_hefwriteword,HEFWriteWord>>,
<<_hefreadblock,HEFReadBlock>>,
<<_hefwriteblock,HEFWriteBlock>>,
<<_heferaseblock,HEFEraseBlock>>
