==== HEFM Overview

*Introduction:*

Some enhanced mid-range Microchip PIC devices support High-Endurance Flash (HEF) memory, some of these devices lack the data EEPROM found on other devices.&#160;&#160;&#160;
Instead, they implement an equivalent amount of special flash memory, called HEF memory, that can provide an endurance comparable to that of a traditional data EEPROM.&#160;&#160;&#160;
This HEF memory appears in the regular program memory space and can be used for any purpose, like regular flash program memory.&#160;&#160;&#160;
{empty} +
{empty} +
As with all flash memory, data must be erased before it can be written and writing this memory will stall the device.&#160;&#160;&#160;
Methods to read, write and erase the HEF memory are included in Great Cow BASIC and they are described in this inroduction.&#160;&#160;&#160;Also see Microchip application note AN1673, Using the PIC16F1XXX High-Endurance Flash (HEF) Block.
{empty} +
{empty} +
Note that by default, Great Cow BASIC will use HEF memory for regular executable code unless it is told otherwise.&#160;&#160;&#160;
If you wish to store data here, you should reserve the HEF memory by using the compiler option, as shown below to reserve 128 words of HEF memory:

----
    #option ReserveHighProg 128
----
HEF memory is a block of memory locations found at the top of the Flash program memory.&#160;&#160;&#160;
Each memory location can be used to hold a variable value, either a byte or a word dependent on *[what?]*.&#160;&#160;&#160;
The main difference between HEF memory and EEPROM is that EEPROM allows byte-by-byte erase whereas the HEF memory does not.&#160;&#160;&#160;
With HEF memory data must be erased before a write and the erase can only be performed in blocks of memory.&#160;&#160;&#160;
The blocks, also called rows, are a fixed size associated with the specific device.&#160;&#160;&#160;
{empty} +
{empty} +
The `hefsaf.h` library supports HEF operations for Great Cow BASIC.


{empty} +
{empty} +
The library provides a set of methods to support use of HEF memory.
{empty} +
{empty} +
[cols="2,^1,3",width="80%"]
|===
|Method
|Parameters
|Usage

|`HEFWrite`
|a subroutine with the paramers: location, byte value
|HEFWrite ( location, byte_variable )

|`HEFWriteWord`
|a subroutine with the paramers: location, word_value
|HEFWriteWord ( location, word_variable  )

|`HEFRead`
|a function with the paramers: location returns a word value
|word_variable = HEFRead ( location  )

|`HEFReadWord`
|a subroutine with the paramers: location, word_value
|HEFRead ( location , word_variable )

|`HEFEraseBlock`
|a subroutine with the paramers: block_number - 0 | 1 | 2 | 3 etc
|HEFEraseBlock ( 0 )

|`HEFWriteBlock`
|a subroutine with the paramers: block_number, buffer_to_used() [, HEF_ROWSIZE_BYTES ]
|HEFWriteBlock( 0, myMemoryBuffer ) 'where myMemoryBuffer is an Array or a String
+
The Array or a String will contain the values to be wrttin to the HEFM.
|`HEFReadBlock`
|a subroutine with the paramers: block_number, buffer_to_used() [, HEF_ROWSIZE_BYTES ]
|HEFReadBlock( 0, myMemoryBuffer ) 'where myMemoryBuffer is an Array or a String.
+
The Array or a String will contain the values from the HEFM.


|===


{empty} +
{empty} +
The library also defines a set constants that are specific to the device.&#160;&#160;&#160;
These may be useful in the user program.
{empty} +
{empty} +
[cols="2,^1,3",width="80%"]
|===
|Constant
|Type
|Usage

|`HEFLASH_ROWSIZE`
|Byte
|Size of an HEFM block in words

|`HEFLASH_START`
|Word
|Starting address of HEFM

|`HEFLASH_END`
|Word
|Ending address of HEFM
|===


*Warning*

Whenever you update the hex file of your Microchip PIC microcontroller with your programmer you MAY erase the data that are stored in HEF memory.&#160;&#160;&#160;
If you want to avoid that you will have to flash your Microchip PIC microcontroller with software that allows memory exclusion when flashing.&#160;&#160;&#160;
This is the case with Microchip PIC MPLAB IPE (Go to `Advanced Mode/Enter password/Select Memory/Tick “Preserve Flash on Program”/
Enter Start and End address` of your HEFM).&#160;&#160;&#160;Or, simply use the PICkitPlus suite of software to preserve HEF memory during programming.
