//erv 04110218
==== HEFMRead


*Syntax:*
[subs="quotes"]
----
    'as a subroutine
    HEFMRead ( location, data )

    'as a function
    data = HEFMRead ( location )
----
*Command Availability:*

Available on all PIC micro-controllers with HEFM memory

*Explanation:*
{empty} +
{empty} +
HEFMRead is used to read information, byte values, from the HFEM data storage, so that it can be accessed for use in a user program.
{empty} +
{empty} +
`location` represents the location to read to - the location will range from location 0 to HEF_WORDS - 1.&#160;&#160;&#160;
HEF_WORDS is Great Cow BASIC defined constant.
{empty} +
`data` is the data that is to be read from the HFEM data storage.&#160;&#160;&#160;
A byte value only.
{empty} +
{empty} +
This method reads data from the HEFM given the specific location the HEFM data storage.&#160;&#160;&#160;
This method is similar to the methods for EEPROM.
{empty} +
{empty} +

*Example 1:*
----
    '... code preamble to select part
    '... code to setup serial

    'The following example reads the HEM value into the byte variable “byte_value”.
    'HEFM byte information is located a position 34.
    HEFread( 34, byte_value )
----

{empty} +
These methods will compute the row number and the offset in the row from the parameter `location` and the Great Cow BASIC constant HEFLASH_ROWSIZE.&#160;&#160;&#160;
This method appropriately handles the management of the HEFM data storage by calculating the correct HEFM page and reading the byte from the appropriate HEFM page.
{empty} +
{empty} +
*Example 2:*
----
    '... code preamble to select part
    '... code to setup serial


    'The following example reads the HEM value into the byte variable “byte_value” using a function.
    'HEFM byte information is located a position 34.
    byte_value = HEFread( 34 )
----

{empty} +
For more information on the Great Cow BASIC constants that support the HEF operations see <<_hefmoverview, HEF Memory Overview>>


{empty} +






*Example 3:*
----


    '... code preamble to select part
    '... code to setup serial

    Dim index, test1, test, row_h, MemLocation as Byte

    HSerPrintCRLF
    HSerPrint "Show HEFM"
    'Call the HEFM_Dump subroutine to read and show the data.
    HEFM_Dump


    End

    ; This subroutine displays the High Endurance Flash Memory on a terminal
    sub HEFM_Dump
        dim MemLocationValue,row, index as word

        for index = 0 to HEF_WORDS - 1
          test=index%8
          test1=index%HEF_ROWSIZE_BYTES
          row=HEF_START_ADDR+index
          if test1 = 0 then
              HSerPrintCRLF
              hserprint "        0"
              hserprint "     1"
              hserprint "     2"
              hserprint "     3"
              hserprint "     4"
              hserprint "     5"
              hserprint "     6"
              hserprint "     7"
          end if
          if test = 0 then
              HSerPrintCRLF
              hserprint hex(row_h)
              hserprint hex(row)
              hserprint "  "
          end if

          'READ THE VALUE!!
          MemLocationValue = HEFRead(row)

          hserprint hex(MemLocationValue_H)
          hserprint hex(MemLocationValue)
          hserprint "  "
        next

        HSerPrintCRLF
    end sub

----
{empty} +
{empty} +
If example 3 where displayed on a serial terminal.&#160;&#160;&#160;The result would show:

----
    Show HEFM
            0     1     2     3     4     5     6     7
    3F00  00FF  00FF  00FF  00FF  00FF  00FF  00FF  00FF
    3F08  00FF  00FF  00FF  00FF  00FF  00FF  00FF  00FF
    3F10  00FF  00FF  00FF  00FF  00FF  00FF  00FF  00FF
    3F18  00FF  00FF  00FF  00FF  00FF  00FF  00FF  00FF
    3F20  00FF  00FF  00FF  00FF  00FF  00FF  00FF  00FF
    3F28  00FF  00FF  00FF  00FF  00FF  00FF  00FF  00FF
    3F30  00FF  00FF  00FF  00FF  00FF  00FF  00FF  00FF
    3F38  00FF  00FF  00FF  00FF  00FF  00FF  00FF  00FF
            0     1     2     3     4     5     6     7
    3F40  00FF  00FF  00FF  00FF  00FF  00FF  00FF  00FF
    3F48  00FF  00FF  00FF  00FF  00FF  00FF  00FF  00FF
    3F50  00FF  00FF  00FF  00FF  00FF  00FF  00FF  00FF
    3F58  00FF  00FF  00FF  00FF  00FF  00FF  00FF  00FF
    3F60  00FF  00FF  00FF  00FF  00FF  00FF  00FF  00FF
    3F68  00FF  00FF  00FF  00FF  00FF  00FF  00FF  00FF
    3F70  00FF  00FF  00FF  00FF  00FF  00FF  00FF  00FF
    3F78  00FF  00FF  00FF  00FF  00FF  00FF  00FF  00FF
            0     1     2     3     4     5     6     7
    3F80  0048  0065  006C  006C  006F  0020  0047  0043
    3F88  0042  0020  0057  006F  0072  006C  0064  0021
    3F90  00FF  00FF  00FF  00FF  00FF  00FF  00FF  00FF
    3F98  00FF  00FF  00FF  00FF  00FF  00FF  00FF  00FF
    3FA0  00FF  00FF  00FF  00FF  00FF  00FF  00FF  00FF
    3FA8  00FF  00FF  00FF  00FF  00FF  00FF  00FF  00FF
    3FB0  00FF  00FF  00FF  00FF  00FF  00FF  00FF  00FF
    3FB8  00FF  00FF  00FF  00FF  00FF  00FF  00FF  00FF
            0     1     2     3     4     5     6     7
    3FC0  00FF  00FF  00FF  00FF  00FF  00FF  00FF  00FF
    3FC8  00FF  00FF  00FF  00FF  00FF  00FF  00FF  00FF
    3FD0  00FF  00FF  00FF  00FF  00FF  00FF  00FF  00FF
    3FD8  00FF  00FF  00FF  00FF  00FF  00FF  00FF  00FF
    3FE0  00FF  00FF  00FF  00FF  00FF  00FF  00FF  00FF
    3FE8  00FF  00FF  00FF  00FF  00FF  00FF  00FF  00FF
    3FF0  00FF  00FF  00FF  00FF  00FF  00FF  00FF  00FF
    3FF8  00FF  00FF  00FF  00FF  00FF  00FF  00FF  00FF
----
{empty} +
{empty} +
See also <<lots of other stuff,lots of other stuff,>>
