==== HEFMWrite Overview


*Syntax:*
[subs="quotes"]
----
    HEFMWrite ( location, data )
----
*Command Availability:*

Available on all microcontrollers with HEFM memory

*Explanation:*
{empty} +
{empty} +
HEFMWrite is used to write information to the HFEM data storage, so that it can be accessed later by a programmer on a Personal, or by the HEFMRead commands.
{empty} +
{empty} +
`location` represents the location to write to - the location will range from location 0 to 255.
`data` is the data that is to be written to the HFEM data storage.&#160;&#160;&#160;A byte value.&#160;&#160;&#160;This can be a byte value or a byte variable.
{empty} +
{empty} +
This method writes information to the HEFM given its relative number in the HEFM date storage .
This method is simimar to the methods for EEPROM.
{empty} +
{empty} +
*Example 1:*
{empty} +
{empty} +
----
    #chip 18F24k42
    'The following example stores in the byte variable “value” the
    'HEFM byte variable located a position 34 with the value of 126
    HEFWrite(34,126 )
----

{empty} +
{empty} +
The method will compute the row number and the offset in the row from `HEFaddress` and HEFLASH_ROWSIZE.
{empty} +
{empty} +
It will then call the HEFWriteBlock subroutine to store the byte data.
{empty} +
{empty} +


*Example 2:*
{empty} +
{empty} +
----
    'This example will populate the 256 bytes of HEF memory with a value that is same as the HEFM location
    Dim HEFaddress as Byte
    For HEFaddress = 0 to 255
        HEFWrite ( HEFaddress, HEFaddress )
    Next
----
{empty} +
{empty} +
If this example where printed to a terminal.&#160;&#160;&#160;The result would show.

----
    Block 0     HEF/SAF Memory View
    3F00   00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F
    3F10   10 11 12 13 14 15 16 17 18 19 1A 1B 1C 1D 1E 1F
    3F20   20 21 22 23 24 25 26 27 28 29 2A 2B 2C 2D 2E 2F
    3F30   30 31 32 33 34 35 36 37 38 39 3A 3B 3C 3D 3E 3F


    Block 1     HEF/SAF Memory View
    3F40   3F 3E 3D 3C 3B 3A 39 38 37 36 35 34 33 32 31 30
    3F50   2F 2E 2D 2C 2B 2A 29 28 27 26 25 24 23 22 21 20
    3F60   1F 1E 1D 1C 1B 1A 19 18 17 16 15 14 13 12 11 10
    3F70   0F 0E 0D 0C 0B 0A 09 08 07 06 05 04 03 02 01 00


    Block 2     HEF/SAF Memory View
    3F80   80 81 82 83 84 85 86 87 88 89 8A 8B 8C 8D 8E 8F
    3F90   90 91 92 93 94 95 96 97 98 99 9A 9B 9C 9D 9E 9F
    3FA0   A0 A1 A2 A3 A4 A5 A6 A7 A8 A9 AA AB AC AD AE AF
    3FB0   B0 B1 B2 B3 B4 B5 B6 B7 B8 B9 BA BB BC BD BE BF


    Block 3     HEF/SAF Memory View
    3FC0   C0 C1 C2 C3 C4 C5 C6 C7 C8 C9 CA CB CC CD CE CF
    3FD0   D0 D1 D2 D3 D4 D5 D6 D7 D8 D9 DA DB DC DD DE DF
    3FE0   E0 E1 E2 E3 E4 E5 E6 E7 E8 E9 EA EB EC ED EE EF
    3FF0   F0 F1 F2 F3 F4 F5 F6 F7 F8 F9 FA FB FC FD FE FF
----
