==== HEFWriteBlock


*Syntax:*
[subs="quotes"]
----
    HEFWriteBlock ( block_number,  buffer(), [, num_bytes] )
----
*Command Availability:*

Available on all PIC micro-controllers with HEFM memory.

*Explanation:*
{empty} +
{empty} +
HEFWriteBlock is used to write information from a user buffer to HEFM.&#160;&#160;&#160;
Once the block is written  it can be accessed for use within a user program.
{empty} +
{empty} +
The parameters are as follows:
{empty} +
{empty} +
`block_number` represents the block to be written to.&#160;&#160;&#160;
The block_number parameter is used to calculate the physical memory location(s) that are updated.
{empty} +
{empty} +
`buffer()` represents any valid array or string.&#160;&#160;&#160;
The buffer will be used as the data source that is written to the HEFM block.&#160;&#160;&#160;
The buffer, an array (or string), is handled as a buffer of bytes values.&#160;&#160;&#160;
in most cases the buffer should be the same size as a row/block of HEFM.&#160;&#160;&#160;
For most PIC Microcontrollers this will be 32 bytes.&#160;&#160;&#160;
For PIC microcontrollers with 2KW or less of Program Memory this will be 16 Bytes.&#160;&#160;&#160;
Best practice is to size the buffer using the HEF_ROWSIZE_BYTES constant.&#160;&#160;&#160;
If the size of the buffer exceeds the device specific HEF_ROWSIZE_BYTES, the excess data will not be handled and the buffer will be truncated at the HEF_ROWSIZE_BYTES limit.&#160;&#160;&#160;
{empty} +
{empty} +
`num_bytes` is an optional parameter, and can be used to specify numeber of bytes to write to HEFM, starting at the first location in the selected HEFM block.&#160;&#160;&#160;
This parameter is not normally required as the default is set to the Great Cow BASIC constant `HEF_ROWSIZE_BYTES`.
{empty} +
{empty} +

*Example 1:*
----
    '... code preamble to select part
    '... code to setup serial

   Dim My_Buffer(HEF_ROWSIZE_BYTES)
   My_Buffer = 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32

    'HEFwriteBlock operation!!
    HEFwriteBlock(2, My_Buffer)

    'A utility method to show the contents of HEFM.
     HEFM_Dump
----
{empty} +
For HEFM_Dump Code, See <<_hefread,HEFRead>>
{empty} +
{empty} +
If example 1 were displayed on a serial terminal.&#160;&#160;&#160;
The result would show. Note the value display at the start of block 2 @ 0x3F80.
----
Block0     0     1     2     3     4     5     6     7
3F80     3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  
3F88     3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  
3F90     3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  
3F98     3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  

Block1     0     1     2     3     4     5     6     7
3FA0     3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  
3FA8     3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  
3FB0     3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  
3FB8     3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  

Block2     0     1     2     3     4     5     6     7
3FC0     3F01  3F02  3F03  3F04  3F05  3F06  3F07  3F08  
3FC8     3F09  3F0A  3F0B  3F0C  3F0D  3F0E  3F0F  3F10  
3FD0     3F11  3F12  3F13  3F14  3F15  3F16  3F17  3F18  
3FD8     3F19  3F1A  3F1B  3F1C  3F1D  3F1E  3F1F  3F20  

Block3     0     1     2     3     4     5     6     7
3FE0     3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  
3FE8     3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  
3FF0     3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  
3FF8     3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  3FFF  

----
{empty} +
{empty} +
See also
<<_hefm_overview,HEFM Overview>>,
<<_hefread,HEFRead>>,
<<_hefreadword,HEFReadWord>>,
<<_hefwrite,HEFWrite>>,
<<_hefwriteword,HEFWriteWord>>,
<<_hefreadblock,HEFReadBlock>>,
<<_hefwriteblock,HEFWriteBlock>>,
<<_heferaseblock,HEFEraseBlock>>
