==== HEFEraseBlock


*Syntax:*
[subs="quotes"]
----
    HEFEraseBlock ( block_number )
----
*Command Availability:*

Available on all PIC micro-controllers with HEFM memory.

*Explanation:*
{empty} +
{empty} +
HEFEraseBlock is used to erase all data locations within the HEFM block.&#160;&#160;&#160; HEFM data within the HEFM block to the erase state value of the device.&#160;&#160;&#160;
This Value is 0xFF and will read 0x3FFF if the entire 14bit program memory word is displayed. 
Use Caution. Once the HEFM block is erased, the HEFM data is gone forever and cannot be recovered unless it was previpusly saved. 
{empty} +
{empty} +
The single parameter is as follows:

`block_number` represents the block to be erased.&#160;&#160;&#160;
The block_number parameter is used to calculate the physical memory location(s) that are updated.
{empty} +
{empty} +

*Example 1:*

Erase a specific block of HEFM.
----
    '... code preamble to select part
    '... code to setup serial, if needed


    'Erase block 2 of HEFM
    HEFEraseBlock ( 2)

----
{empty} +
{empty} +
See also
<<_hefm_overview,HEFM Overview>>,
<<_hefread,HEFRead>>,
<<_hefreadword,HEFReadWord>>,
<<_hefwrite,HEFWrite>>,
<<_hefwriteword,HEFWriteWord>>,
<<_hefreadblock,HEFReadBlock>>,
<<_hefwriteblock,HEFWriteBlock>>,
<<_heferaseblock,HEFEraseBlock>>

