//erv 04110218
==== HEFReadWord


*Syntax:*
[subs="quotes"]
----
    'as a subroutine
    HEFReadWord ( location, data_word_variable )

    'as a function
    data_word_variable = HEFReadWord ( location )
----
*Command Availability:*

Available on all PIC micro-controllers with HEFM memory

*Explanation:*
{empty} +
{empty} +
HEFReadWord is used to read information, word values, from HEFM so that it can be accessed for use in a user program.
{empty} +
{empty} +
`location` represents the location or relative address to read.  The location will range from location 0 to HEF_BYTES - 1, or for all practical purposes 0-127 since all PIC Microcontrollers with HEF support 128 bytes of HEF Memory. HEF_BYTES is a Great Cow BASIC constant that represents the number of bytes of HEF Memory.&#160;&#160;&#160;
{empty} +
{empty} +
`data` is the data that is to be read from the HEFM data storage.&#160;&#160;&#160;
This must be a word variable.&#160;&#160;&#160;
{empty} +
{empty} +
This method reads data from HEFM given the specific relative location.&#160;&#160;&#160;
{empty} +
{empty} +
*Example 1:*
----
    '... code preamble to select part
    '... code to setup serial

    'The following example reads the HEFM value into the word variable “data_word_variable” by initially writing some word values.

    dim data_word_variable as word
    HEFWriteWord( 254, 4660 )

    HEFReadWord( 254, data_word_variable )

    HSerPrint "Value = "
    HSerPrint data_word_variable
    HSerPrintCRLF

----
{empty} +
If example 1 were displayed on a serial terminal.&#160;&#160;&#160;The result would show:

----
    Value = 4660
----
{empty} +
{empty} +
*Example 2:*
----
    '... code preamble to select part
    '... code to setup serial

    'The following example uses a function to read the HEFM value into the word variable “data_word_variable”.

    dim data_word_variable as word
    HEFWriteWord( 254, 17185 )

    data_word_variable = HEFReadWord( 254 )

    HSerPrint "Value = "
    HSerPrint data_word_variable
    HSerPrintCRLF

----
{empty} +
If example 2 were displayed on a serial terminal.&#160;&#160;&#160;The result would show:

----
    Value = 17185
----

{empty} +
{empty} +
See also
<<_hefm_overview,HEFM Overview>>,
<<_hefread,HEFRead>>,
<<_hefreadword,HEFReadWord>>,
<<_hefwrite,HEFWrite>>,
<<_hefwriteword,HEFWriteWord>>,
<<_hefreadblock,HEFReadBlock>>,
<<_hefwriteblock,HEFWriteBlock>>,
<<_heferaseblock,HEFEraseBlock>>
