==== HSerPrintStringCRLF

*Syntax:*
[subs="quotes"]
----
    HSerPrintStringCRLF _user_string_ [,1|2|3|4]  'Choose comport with optional parameter
                                                'Default comport is 1
----
*Command Availability:*

Available on all microcontrollers with a USART or UART module. +

Microchip PIC supports USART1 and 2. +
Atmel AVR supports USART 1,2,3 and 4.

*Enabling Constants:*

To enable the use of the USART these are the enabling constants. &#160;&#160;These constants are required.&#160;&#160;You can change the `USART_BAUD_RATE` and to meet your needs.&#160;&#160;For addition USART ports use `#define USART**n**_BAUD_RATE 9600` where `**n**`` is the required port number.

----
    'USART settings for USART1
    #define USART_BAUD_RATE 9600
    #define USART_TX_BLOCKING
    #define USART_DELAY OFF
----

*Explanation:*

`HSerPrintStringCRLF` is used to send a string over the serial connection. The parameter can only
 be a string. `HSerPrintStringCRLF` is very similar to `HserPrint` but `HserPrint` can handle all types of variables.

The data will be sent out the hardware serial module.

`HSerPrintStringCRLF` will send new line characters:

[subs="quotes"]

*Example:*
----
  'This program will display string over the serial connection.

  'Chip settings
  #chip 18F2525, 8

  'USART settings
  #define USART_BAUD_RATE 9600
  #define USART_TX_BLOCKING

  'Show string message
  HSerPrintStringCRLF "Great Cow BASIC RS232 Test"
  Wait 1 s


----
*For more help, see also*
<<_hserprint,HserPrint>>, <<_hserprintbytecrlf,HserPrintByteCRLF>> *and* <<_hserprintcrlf,HserPrintCRLF>>
