==== InitTimer4

*Syntax: (MicroChip PIC)*
[subs="quotes"]
----
    InitTimer4 _prescaler_, _postscaler_

or, where you required to state the clock source, use the following

    InitTimer4 _clocksource_, _prescaler_, _postscaler_

----

*Syntax: (Atmel AVR)*
[subs="quotes"]
----
    InitTimer4 _source_, _prescaler_
----


*Command Availability:*

Available on all microcontrollers with a Timer 4 module.&#160;&#160;As shown above a Microchip microcontroller can potentially support two types of methods for initialisation.
{empty} +
{empty} +
The first method is:
{empty} +
----
    InitTimer4 prescaler, postscaler
----
This the most common method to initialise a Microchip microcontroller timer.&#160;&#160;With this method the timer has only one possible clock source, this mandated by the microcontrollers architecture, and that clock source is the System Clock/4 also known as FOSC/4.
{empty} +
{empty} +
{empty} +
The second method is much more flexible in term of the clock source.&#160;&#160;Microcontrollers that support this second method enable you to select different clock sources and to select more prescale values.&#160;&#160;The method is shown below:
{empty} +
----
    InitTimer4 clocksource, prescaler, postscaler
----
**How do you determine which method to use for your specific Microchip microcontroller ?**
{empty} +
{empty} +
The timer type for a Microchip microcontroller can be determined by checking for the existance of a T2CLKCON register, either in the Datasheet or in the Great Cow BASIC  "dat file" for the specific device.
{empty} +
{empty} +
If the Microchip microcontroller **DOES NOT** have a T4CLKCON register then timers 2/4/6/8 for that specific microcontroller chip use the first method, and are configured using:
{empty} +
----
    InitTimer4 (PreScale, PostScale)
----
If the microcontroller **DOES** have a T2CLKCON register then ALL timers 2/4/6/8 for that specific microcontroller chip use the second method, and are configured using:
----
    InitTimer4 (Source,PreScale,PostScale)
----
The possible Source, Prescale and Postscale constants for each type are shown in the tables below.&#160;&#160;These table are summary tables from the Microchip datasheets.
{empty} +
{empty} +

**Period of the Timers**

The Period of the timer is determined by the system clock speed, the prescale value and 8-bit value in the respective timer period register.&#160;&#160;The timer period for timer 4 is held in register PR4.&#160;&#160;
{empty} +

When the timer is enabled, by starting the timer, it will increment until the TMR4 register matches the value in the PR4 register.&#160;&#160;At this time the TMR4 register is cleared to 0 and the timer continues to increment until the next match, and so on.
{empty} +

The lower the value of the PR4 register, the shorter the timer period will be.&#160;&#160;The default value for the PR4 register at power up is 255.
{empty} +

The timer interrupt flag (TMR4IF) is set based upon the number of match conditions as determine by the postscaler.&#160;&#160;The postscaler does not actually change the timer period, it changes the time between interrupt conditions.
{empty} +
{empty} +

*Timer constants for the MicroChip microcontrollers*

Parameters for this timer are detailed in the tables below:

[cols=2, options="header,autowidth"]

|===

|Parameter
|Description

|`_clocksource_`
|If required by method select.
&#160; +
Source can be one of the following numeric values: +
&#160; +
         1 equates to OSC (FOSC/4). &#160;&#160;&#160;The default clock source +
         +
         6 equates to EXTOSC same as SOSC +
         5 equates to MFINTOSC +
         4 equates to LFINTOSC +
         3 equates to HFINTOSC +
         2 equates to FOSC +
         1 equates to FOSC/4 same as OSC +
         0 equates to TxCKIPPS same as EXTOSC and EXT (T1CKIPPS) +

Other sources may be available but can vary from microcontroller to microcontroller and these can be included manually per the specific microcontrollers datasheet.

|`_prescaler_`
|The value of the prescaler for this specific timer.  See the tables below for permitted values.


|`_postscaler_`
|The value of the postscaler for this specific timer.  See the tables below for permitted values.

|===
*Table 1 shown above*

{empty} +
{empty} +


`prescaler` can be one of the following settings, if you MicroChip microcontroller has the T4CKPS4 bit then refer to table 2:

[cols="^1,1,^1", options="header,autowidth"]
|===
|*Prescaler Value*
|*Primary GCB Constant*
|*Constant Equates +
to value*

|1:1
|`PS4_1`
|0

|1:4
|`PS4_4`
|1

|1:16
|`PS4_16`
|2

|1:64
|`PS4_64`
|3

|===
*Table 2*

Note that a 1:64 prescale is only avaialable on certain midrange microcontrollers.
Please refer to the datasheet to determine if a 1:64 prescale is supported by a
spectific microcontroller.
{empty} +
{empty} +
[cols="^1,1,^1", options="header,autowidth"]
|===
|*Prescaler Value*
|*Primary GCB Constant*
|*Constant Equates +
to value*

|1:1
|`PS4_1`
|0

|1:2
|`PS4_2`
|1

|1:4
|`PS4_4`
|2

|1:8
|`PS4_8`
|3

|1:16
|`PS4_16`
|4

|1:32
|`PS4_32`
|5

|1:64
|`PS4_64`
|6

|1:128
|`PS4_128`
|7


|===
*Table 3*
{empty} +
{empty} +

`_postscaler_` slows the rate of the interrupt generation (or WDT reset) from a
counter/timer by dividing it down.

On Microchip PIC microcontroller one of the following constants where the Postscaler Rate Select bits are in the range of 1 to 16.

[cols="^1,^1", options="header,autowidth"]
|===
|*Postcaler Value*
|*Use Numeric Constant*


|1:1 Postscaler
|0

|1:2 Postscaler
|1

|1:3 Postscaler
|2

|1:4 Postscaler
|3

|1:5 Postscaler
|4

|1:6 Postscaler
|5

|1:7 Postscaler
|6

|1:8 Postscaler
|7

|1:9 Postscaler
|8

|1:10 Postscaler
|9

|1:11 Postscaler
|10

|1:12 Postscaler
|11

|1:13 Postscaler
|12

|1:14 Postscaler
|13

|1:15 Postscaler
|14

|1:16 Postscaler
|15

|===


{empty} +
{empty} +

*Explanation:(Atmel AVR)*

`InitTimer4` will set up timer 4, according to the settings given.

`source` can be one of the following settings:
Parameters for this timer are detailed in the table below:

[cols=2, options="header,autowidth"]

|===

|Parameter
|Description

|`_source_`
|The clock source for this specific timer. Can be either `Osc` or `Ext` where`Osc` is an internal oscillator and `Ext` is an external oscillator.

|===

{empty} +
{empty} +


`prescaler` for Atmel AVR Timer 4 can be selected from the table below.

Prescaler Rate Select bits are in the range of 1 to 1024

[cols="^1,1,1,^1", options="header,autowidth"]
|===
|*Prescaler Value*
|*Primary GCB Constant*
|*Secondary GCB Constant*
|*Constant Equates +
to value*

|1:0
|`PS_0`
|`PS_4_0`
|1


|1:1
|`PS_1`
|`PS_4_1`
|1

|1:8
|`PS_8`
|`PS_4_8`
|2

|1:64
|`PS_64`
|`PS_4_64`
|3

|1:256
|`PS_256`
|`PS4_256`
|4

|1:1024
|`PS_1024`
|`PS_4_1024`
|5

|===
{empty} +
{empty} +
{empty} +


*Example:*

This code uses Timer 4 and On Interrupt to generate a 1ms pulse 20 ms.
----
    #chip 18F25K80, 8

    #DEFINE PIN3 PORTA.1
    DIR PIN3 OUT

    #Define Match_Val PR4  'PR4 is the timer 2 match register
    Match_Val = 154        'Interrupt afer 154 Timer ticks (~20ms)

    On interrupt timer4Match call PulsePin3  'Interrupt on match
    Inittimer4 PS4_16, 15 'Prescale 1:64 /Postscale 1:16 (15)
    Starttimer 4

    Do
       'Waiting for interrupt on match val of 154
    Loop

    Sub PulsePin3
       pulseout Pin3, 1 ms
    End Sub
----
