===== LCD_IO 4

*Using connection mode 4:*

To use connection mode 4 the R/W, RS, Enable control lines and the highest 4 data lines (DB4 through DB7) must be connected to the microcontroller.

*Relevant Constants:*

Specific constants are used to control settings for the Liquid Crystal Display routines included with Great Cow BASIC.  To set these constants the main program should specific constants to support the connection mode using #define.
Constants required for connection mode 4.

Constants are required for 4-bit mode as follows.
[cols=3, options="header,autowidth"]
|===
|*Constant Name*
|*Controls*
|*Default Value*

|`LCD_SPEED`
|`FAST`, `MEDIUM` or `SLOW`.
|`MEDIUM`

|`LCD_IO`
|Must be *4*
|`4`

|`LCD_RS`
|Specifies the output pin that is connected to Register Select on the
LCD.
|Must be defined as `port.bit`

|`LCD_RW`
|Specifies the output pin that is connected to Read/Write on the LCD. The
R/W pin can be disabled*.
|Must be defined as `port.bit` _(unless R/W is disabled)_

|`LCD_Enable`
|Specifies the output pin that is connected to Read/Write on the LCD.
|Must be defined as `port.bit`

|`LCD_DB4`
|Output pin used to interface with bit 4 of the LCD data bus
|Must be defined as `port.bit`

|`LCD_DB5`
|Output pin used to interface with bit 5 of the LCD data bus
|Must be defined as `port.bit`

|`LCD_DB6`
|Output pin used to interface with bit 6 of the LCD data bus
|Must be defined as `port.bit`

|`LCD_DB7`
|Output pin used to interface with bit 7 of the LCD data bus
|Must be defined as `port.bit`

|
|
|

|`LCD_VFD_DELAY`
|Specifies a delay between transmission of data nibbles to LCD or VFD.

Usage must include number value and unit of time.

`#DEFINE LCD_VFD_DELAY 1 ms`

Only applicable when using LCD_IO 4
|None.



|===

The `R/W` pin can be disabled by setting the `LCD_NO_RW` constant. If this
is done, there is no need for the `R/W` to be connected to the chip, and
no need for the `LCD_RW` constant to be set. Ensure that the `R/W` line on
the LCD is connected to ground if not used.



For a code example download http://gcbasic.sourceforge.net/library/DEMO%20CODE/Demo%20code%20for%20lcd/Demo%20mode%204.gcb[Four Wire LCD Example].

Also see for further code examples see http://github.com/Anobium/Great-Cow-BASIC-Demonstration-Sources/tree/master/LCD_Solutions[Four Wire LCD Solutions].

See the separate sections of the Help file for the specifics of each
Connection Mode.

*For more help, see*
<<_lcd_io_0,LCD_IO 0>>, <<_lcd_io_1,LCD_IO 1>>, <<_lcd_io_2,LCD_IO 2>>,
<<_lcd_io_2_74xx164,LCD_IO 2_74xx164>>, <<_lcd_io_2_74xx174,LCD_IO 2_74xx174>>,
<<_lcd_io_8,LCD_IO 8>>,
<<_lcd_io_10,LCD_IO 10>> or <<_lcd_io_12,LCD_IO 12>>
