===== LCD_IO 1

*Using connection mode 1:*

This approach uses a single connectivity line that supports a combined data
and clock signal between the microcontroller and the LCD display. This approach
is used when the LCD is connected through a shift register 74HC595, as detailed
at http://gcbasic.sourceforge.net/library/DIAGRAMS/1-Wire%20LCD/1-wire%20LCD%2074HC595%20for%20GCB.jpg[here].
This connection method is also called a 1-wire connection.

This solution approach recognises the original work provided in the Elektor Magazine.

*Relevant Constants:*

Specific constants are used to control settings for the Liquid Crystal Display routines included with Great Cow BASIC. To set these constants the main program should specific constants to support the connection mode using #define.

When using connection mode 1, only two constants must be set - all others are optional or can be ignored.


How to connect and control the LCD background led: see <<_lcdbacklight, LCDBacklight>>.


[cols=3, options="header,autowidth"]
|===
|*Constant Name*
|*Controls*
|*Default Value*

|`LCD_IO`
|The I/O mode.
|`1`

|`LCD_CD`
|The clock/data pin used in 1-bit mode.
|*Mandated*

|===


LCD.h supports in 1-wire mode the control of pin 4 of the 74HC595 for the background led.

For a code example download http://gcbasic.sourceforge.net/library/DEMO%20CODE/Demo%20code%20for%20lcd/Demo%20mode%201.gcb[One Wire LCD Example].

See for further code examples see http://github.com/Anobium/Great-Cow-BASIC-Demonstration-Sources/tree/master/LCD_Solutions[0,1 and 2 Wire LCD Solutions].

See the separate sections of the Help file for the specifics of each Connection Mode.


*For more help, see*
<<_lcd_io_0,LCD_IO 0>>, <<_lcd_io_2,LCD_IO 2>>
<<_lcd_io_2_74xx164,LCD_IO 2_74xx164>>, <<_lcd_io_2_74xx174,LCD_IO 2_74xx174>>
<<_lcd_io_4,LCD_IO 4>>, <<_lcd_io_8,LCD_IO 8>>,
<<_lcd_io_10,LCD_IO 10>> or <<_lcd_io_12,LCD_IO 12>>