===== LCD_IO 10

*Using connection mode 10:*

The LCD is controlled via I2C of a type 10 LCD 12C adapter.
Use LCD_IO 10 for the YwRobot LCD1602 IIC V1 or the Sainsmart LCD_PIC I2C adapter.
To use mode 10 you must define the I2C ports as normal in your Great Cow BASIC code.
Then, define the LCD type, set the I2C_address of the LCD adapter and the LCD speed, if required.
Finally, set the backlight control, if required.

*Relevant Constants:*

These constants are used to control settings for the Liquid Crystal Display routines included with Great Cow BASIC. To set them, place a line in the main program file that uses #define to assign a value to the particular constant.

[cols=3, options="header,autowidth"]
|===
|*Constant Name*
|*Controls*
|*Value*

|`LCD_IO`
|The I/O mode. Must be 10
|`10`

|`LCD_I2C_Address_1`
|Address of I2C adapter
|Default `0x4E`

|`LCD_I2C_Address_2`
|Address of I2C adapter
|Not set

|`LCD_I2C_Address_3`
|Address of I2C adapter
|Not set

|`LCD_I2C_Address_4`
|Address of I2C adapter
|Not set
|===

For code examples see http://github.com/Anobium/Great-Cow-BASIC-Demonstration-Sources/tree/master/LCD_Solutions[I2C LCD Solutions].

See the separate sections of the Help file for the specifics of each
Connection Mode.

*For more help, see*
<<_lcd_io_0,LCD_IO 0>>, <<_lcd_io_1,LCD_IO 1>>, <<_lcd_io_2,LCD_IO 2>>,
<<_lcd_io_2_74xx164,LCD_IO 2_74xx164>>, <<_lcd_io_2_74xx174,LCD_IO 2_74xx174>>,
<<_lcd_io_4,LCD_IO 4>>, <<_lcd_io_8,LCD_IO 8>>, <<_lcd_io_12,LCD_IO 12>>
