=== Overview

*Introduction:*
Great Cow BASIC can be used when using the Apple macOS operatimg system.

This instructions are for macOS only (not Windows).

You have a choice to make. You can either:

. download a macOS installer which will install a precompiled binary for Great Cow BASIC along with support files and some optional components; or
. download, compile and install Great Cow BASIC from the source files.

There are instructions below for both choices.

*Instructions for using the Great Cow BASIC Installer*

[start=1]
 . Download the Great Cow BASIC - macOS Installer disk image (.dmg) file from
  [^^ADD LOCATION^^]

 . Double click the .dmg file to mount it on your Desktop and a window will open which contains the .pkg Installer.

 . Double click the .pkg Installer and follow the prompts.

*Instructions for building your own Great Cow BASIC binary*

Complete the following steps to compile and install Great Cow BASIC:

[start=1]
 . Download the FreeBASIC 1.06 macOS 10.4 binary compilation from: http://tmc.castleparadox.com/temp/fbc-1.06-darwin-wip20160505.tar.bz2

 . Download the "Great Cow BASIC - macOS Distribution" from SourceForge at https://sourceforge.net/projects/gcbasic/files/

 . Unfortunately Apple replaced the gcc compiler with the clang compiler and FreeBASIC needs the real gcc due to a certain use of goto... so, you can compile your own version of gcc following the instructions at: https://bitbucket.org/sol_prog/macos-gcc-binary or you can take the low road and just download the pre-compiled binary version from https://bitbucket.org/sol_prog/macos-gcc-binary/raw/38724f2d24aa5b7944d2227d8098b1d30ac5d7b5/gcc-8.1.tar.bz2

 . Open a Terminal window (Terminal can be found in Applications > Utilities).

 . Move gcc-8.1.tar.bz2 from your Downloads directory to your Home directory by typing the following command in your Terminal window:
----
   mv ~/Downloads/gcc-8.1.tar.bz2 ~/
----

[start=6]
 . Unpack the gcc-8.1.tar.bz2 compressed tar file by typing the following comamnd into your Terminal window: 
----
   gzcat gcc-8.1.tar.bz2 | tar xvf -
----
This will produce a gcc-8.1 directory.

[start=7]
 . Move the gcc-8.1 directory to the /usr/local/ directory by typing the following commands into your Termainl window:
----
   sudo mv gcc-8.1 /usr/local
----
Note: You will be asked for your password to execute the above command.

[start=8]
 . Ensure that the latest Apple Developer Xcode app is installed. Xcode is available from the App Store for free. 

[start=9]
 . Ensure that the XCode command line tools are installed by typing the following command in your Terminal window:
----
   xcode-select --install.
----

[start=10]
 . Move the FreeBASIC compressed tar file from your Downloads directory to your home directory by typing the following command in your Terminal window:
----
   mv ~/Downloads/fbc-1.06-darwin-wip20160505.tar.bz2 ~/
----

[start=11]
 . Unpack the FreeBASIC compressed tar file by typing these commands in your Terminal window:
----
   gzcat fbc-1.06-darwin-wip20160505.tar.bz2 | tar xvf -
----
which will produce a new directory called fbc-1.06.

[start=12]
 . Move the Great Cow BASIC compressed tar file from your Downloads directory to your home directory by typing the following command in your Terminal window:
----
   mv ~/Downloads/GCB-macOS.tar.bz2 ~/
----

[start=13]
 . Unpack the Great Cow BASIC compressed tar file by typing these commands in your Terminal window:
----
   gzcat GCB-macOS.tar.bz2 | tar xvf -
----
which will produce a new directory called GreatCowBasic.

[start=14]
 . Change to the ~/GreatCowBasic/Sources directory by typing this command in your Terminal window:
----
   cd ~/GreatCowBasic/Sources
----

[start=15]
 . Confirm proper execution, and the version, of Great Cow BASIC by typing the following command in the Terminal window:
----
   gcbasic /version
----

Now you can create and compile GCB source files.



*Programming microcontrollers:*

To program your microcontroller with your Great Cow BASIC-created hex file, you will need additional software.

For Microchip PIC microcontroller programming, you might find what you need at: http://www.microchip.com/DevelopmentTools/ProductDetails.aspx?PartNO=pg164120

For Atmel AVR microcontroller programming, you will need `avrdude`. It should be available in your distributions repository. If not, check here: http://www.nongnu.org/avrdude/

