==== Parabola:

*Syntax:*
[subs="quotes"]
----
    Parabola (x_0,  y_0,  p_factor,  type, ModeStop, optional LineColour=GLCDForeground)
----
*Explanation:*

Draws on a GLCD a parabola with equation y^2=2*p_factor*x, centered at  pixel positions (x_0, y_0) .

The parabola can be alined either along the x axis or along the y axis.

The parabola is an unbounded curve.
Drawing parabola on the screen can be stopped by following two different criteria:
	-  a branch has reached a border of the display
	- both branches have reached the display border
For a parabola centered on the display these criteria are equivalent.

'** Input parameters:
'**       (x_0, y_0) = coordinates (x, y) of the parabola vertex  (i.e., the minimum x value when alined along x
			    or the minimum y value when alined along y (in pixel positions)
'**       p_factor = the factor such that y^2=2*p_factor*x is the equation of the parabola
'**       Type :
			Type=1 the parabola is aligned along x axis
			Type=2 the parabola is aligned along y axis
'**	  ModeStop:
			ModeStop=1 drawing stops when a display border is encountered by a parabola branch.
'**		    	ModeStop=2 drawing stops when all the reachable display borders are encountered by both the parabola branches
'**	  LineColour: Color of the Hyperbole drawing


*Example:*
----
	A 240x320 pixels GLCD is referred to

    #include <glcd.h>

    Parabola(120, 160, 20, 1, 2, GLCDForeground)   ;   centered, p_factor=20, x_axis alined, stops when all branches have reached a a border
    Parabola(120, 160 ,20, 1, 1, GLCDForeground)   ; centered, p_factor=20, x_axis alined, stops when a border is reached
    Parabola(120, 160, 20, 2, 1, GLCDForeground)   ; centered, p_factor=20, y_axis alined, stops when a border is reached,

    Parabola(180, 80, 20, 1, 1, GLCDForeground)   ; upper right, p_factor=20, x_axis alined, stops when a border is touched,
    Parabola(60, 240, 20, 1, 2, GLCDForeground)   ; lower left, p_factor=20, x_axis alined, stops when all branches have reached a border

    Parabola(180, 80, 20, 2, 1, GLCDForeground)   ; upper right, p_factor=20, y_axis alined, stops when a border is touched,
    Parabola(60, 240, 20, 2, 2, GLCDForeground)   ; lower left, p_factor=20, y_axis alined, stops when all branches have reached a border
