=== ReadTable

*About ReadTable*

The `ReadTable` command is used to read information from lookup tables.
`_TableName_` is the name of the table that is to be read, `_Item_` is the
line of the table to read, and `_Output_` is the variable to write the
retrieved value in to.

*Syntax:*
[subs="quotes"]
----
    ReadTable _TableName, Item, Output_
----
*Command Availability:*

Available on all microcontrollers.

*Explanation:*

`_Item_` is 1 for the first line of the table, 2 for the second, and so on.
If the Table is more than 256 elements then `_Item_` must be WORD variable.
Care must be taken to ensure that the program is not instructed to read beyond the end of the table as Zero will be returned.

The type of `_Output_` should match the type of data stored in the table.
For example, if the table contains Word values then `_Output_` should be a
Word variable. If the type does not match, Great Cow BASIC will attempt to
convert the value.

*Example:*
----
    'Chip Settings
    #chip 16F88, 20

    'Hardware Settings
    #define LED PORTB.0
    Dir LED Out

    'Main Routine
    ReadTable TimesTwelve, 4, Temp
    Set LED Off
    If Temp = 48 Then Set LED On

    'Lookup table named "TimesTwelve"
    Table TimesTwelve
    12
    24
    36
    48
    60
    72
    84
    96
    108
    120
    132
    144
    End Table
----
*For more help, see* <<_lookup_tables,Lookup Tables>>
