//erv 04110218
==== SAFRead


*Syntax:*
[subs="quotes"]
----
    'as a subroutine
    SAFRead ( location, data )

    'as a function
    data = SAFRead ( location )
----
*Command Availability:*

Available on all PIC micro-controllers with SAFM memory

*Explanation:*
{empty} +
{empty} +
SAFRead is used to read information, byte values, from SAFM, so that it can be accessed for use in a user program.
{empty} +
{empty} +
`location` represents the location or relative address to read.  The location will range from location 0 to SAF_BYTES - 1. This cab be from 0-127 or 0-255m depending upon the specific device. HEF_BYTES is a Great Cow BASIC constant that represents the number of bytes of SAF Memory.&#160;&#160;&#160;
{empty} +
{empty} +
`data` is the data that is to be read from the SAFM data storage area.&#160;&#160;&#160;
This can be a byte value or a byte variable.
{empty} +
{empty} +
This method reads data from SAFM given the specific relative location.&#160;&#160;&#160;
This method is similar to the EPRead method for EEPROM.
{empty} +
{empty} +
*Example 1:*
----
    '... code preamble to select part
    '... code to setup serial
    '... code to setup PPS

    'The following example reads the data at SAF location 34 into the byte variable “byte_value”.
    'SAFM byte information is in SAF location 34.

     SAFRead( 34, byte_value )
----
{empty} +
{empty} +
*Example 2:*
----
    '... code preamble to select part
    '... code to setup serial
    '... code to setup PPS


    'The following example reads the HEM value into the byte variable “byte_value” using a function.
    'SAFM byte information is located a position 34.
    byte_value = SAFread( 34 )
----
{empty} +
{empty} +
*Example 3:*
----

    '... code preamble to select part
    '... code to setup serial
    '... code to setup PPS

    Dim Rel_Address,DataByte, Index as Byte
    Dim NVM_Address as Long  ' Absolute Address
    Dim  DataWord, as Word
    Dim MyBuffer(SAF_ROWSIZE_BYTES)
    
    HSerPrintCRLF
    HSerPrint "Show SAFM"
    'Call the SAFM_Dump subroutine to read and show the data.
    SAFM_Dump
    End

   ; This subroutine displays the Storage Area Memory of PIC 18F24K42 on a terminal.
   ; Words are in reverse byte order relative to address.
       
    sub SAFM_Dump

    Dim Blocknum as Byte
    NVM_Address  = SAF_START_ADDR
    BlockNum = 0

    Repeat SAF_BYTE_WORDS    
        If NVM_Address % SAF_ROWSIZE_BYTES = 0 then
           If BlockNum > 0 then   HSERPRINTCRLF
           HSerprintCRLF

           HserPrint "Block"
           HSerprint BlockNum
           HSerprint "  1 0   3 2   5 4   7 6   9 8   B A   D C   F E"
           BlockNum++
        End if

        IF NVM_Address  % 16 = 0 then
           HSerPrintCRLF
           hserprint hex(NVM_Address_H)
           hserprint hex(NVM_Address)
           hserprint "    "
        end if

        Rel_Address = NVM_ADDRESS - SAF_START_ADDR
        SAFReadWord(Rel_Address,DataWord)

        hserprint hex(DataWord_H)
        hserprint hex(DataWord)
        hserprint "  "

        NVM_Address+=2 ' Next "WORD"
    End Repeat

 HserPrintCRLF

End sub
----
{empty} +
{empty} +
If example 3 were displayed on a serial terminal.&#160;&#160;&#160;The result would show:

----
    Show SAFM
Block0  1 0   3 2   5 4   7 6   9 8   B A   D C   F E
7F00    FFFF  FFFF  FFFF  FFFF  FFFF  FFFF  FFFF  FFFF  
7F10    FFFF  FFFF  FFFF  FFFF  FFFF  FFFF  FFFF  FFFF  
7F20    FFFF  FFFF  FFFF  FFFF  FFFF  FFFF  FFFF  FFFF  
7F30    FFFF  FFFF  FFFF  FFFF  FFFF  FFFF  FFFF  FFFF  

Block1  1 0   3 2   5 4   7 6   9 8   B A   D C   F E
7F40    FFFF  FFFF  FFFF  FFFF  FFFF  FFFF  FFFF  FFFF  
7F50    FFFF  FFFF  FFFF  FFFF  FFFF  FFFF  FFFF  FFFF  
7F60    FFFF  FFFF  FFFF  FFFF  FFFF  FFFF  FFFF  FFFF  
7F70    FFFF  FFFF  FFFF  FFFF  FFFF  FFFF  FFFF  FFFF  

Block2  1 0   3 2   5 4   7 6   9 8   B A   D C   F E
7F80    FFFF  FFFF  FFFF  FFFF  FFFF  FFFF  FFFF  FFFF  
7F90    FFFF  FFFF  FFFF  FFFF  FFFF  FFFF  FFFF  FFFF  
7FA0    FFFF  FFFF  FFFF  FFFF  FFFF  FFFF  FFFF  FFFF  
7FB0    FFFF  FFFF  FFFF  FFFF  FFFF  FFFF  FFFF  FFFF  

Block3  1 0   3 2   5 4   7 6   9 8   B A   D C   F E
7FC0    FFFF  FFFF  FFFF  FFFF  FFFF  FFFF  FFFF  FFFF  
7FD0    FFFF  FFFF  FFFF  FFFF  FFFF  FFFF  FFFF  FFFF  
7FE0    FFFF  FFFF  FFFF  FFFF  FFFF  FFFF  FFFF  FFFF  
7FF0    FFFF  FFFF  FFFF  FFFF  FFFF  FFFF  FFFF  FFFF  
----
{empty} +
{empty} +
See also
<<_safm_overview,SAFM Overview>>,
<<_safread,SAFRead>>,
<<_safreadword,SAFReadWord>>,
<<_safwrite,SAFWrite>>,
<<_safwriteword,SAFWriteWord>>,
<<_safreadblock,SAFReadBlock>>,
<<_safwriteblock,SAFWriteBlock>>,
<<_saferaseblock,SAFEraseBlock>>
