//erv 04110218
==== SAFRead


*Syntax:*
[subs="quotes"]
----
    'as a subroutine
    SAFRead ( location, data )

    'as a function
    data = SAFRead ( location )
----
*Command Availability:*

Available on all PIC micro-controllers with SAFM memory

*Explanation:*
{empty} +
{empty} +
SAFRead is used to read information, byte values, from SAFM, so that it can be accessed for use in a user program.
{empty} +
{empty} +
`location` represents the location or relative address to read.  The location will range from location 0 to SAF_BYTES - 1. This cab be from 0-127 or 0-255m depending upon the specific device. HEF_BYTES is a Great Cow BASIC constant that represents the number of bytes of SAF Memory.&#160;&#160;&#160;
{empty} +
{empty} +
`data` is the data that is to be read from the SAFM data storage area.&#160;&#160;&#160;
This can be a byte value or a byte variable.
{empty} +
{empty} +
This method reads data from SAFM given the specific relative location.&#160;&#160;&#160;
This method is similar to the EPRead method for EEPROM.
{empty} +
{empty} +
*Example 1:*
----
    '... code preamble to select part
    '... code to setup serial
    '... code to setup PPS

    'The following example reads the SAFM data value into the byte variable “byte_value” using a subroutine.
    
    Dim data_byte as byte
    
    ;Write a byte of data to SAF Location 34
    SAFWrite( 34, 144)
    
    ;Read the byte back from SAF location 34   
    byte_value = SAFread( 34 )
    
    ;Display the data on a terminal
    HserPrint "byte_value = "
    Hserprint byte_value

----
{empty} +
{empty} +
*Example 2:*
----
    '... code preamble to select part
    '... code to setup serial
    '... code to setup PPS

    'The following example reads the SAFM data value into the byte variable “byte_value” using a function.
    
    Dim data_byte as byte
    
    ;Write a byte of Data to SAF Location 34
    SAFWrite( 34, 144)
    
    ;Read the byte back from SAF location 34   
    byte_value = SAFread( 34 )
    
    ;Display the data on a terminal
    HserPrint "byte_value = "
    Hserprint byte_value
----
{empty} +
{empty} +
See also
<<_safm_overview,SAFM Overview>>,
<<_safread,SAFRead>>,
<<_safreadword,SAFReadWord>>,
<<_safwrite,SAFWrite>>,
<<_safwriteword,SAFWriteWord>>,
<<_safreadblock,SAFReadBlock>>,
<<_safwriteblock,SAFWriteBlock>>,
<<_saferaseblock,SAFEraseBlock>>
