//erv 04110218
==== SAFReadWord


*Syntax:*
[subs="quotes"]
----
    'as a subroutine
    SAFReadWord ( location, data_word_variable )

    'as a function
    data_word_variable = SAFReadWord ( location )
----
*Command Availability:*

Available on all PIC micro-controllers with SAFM memory

*Explanation:*
{empty} +
{empty} +
SAFReadWord is used to read information, word values, from the SAFM data storage, so that it can be accessed for use in a user program.
{empty} +
{empty} +
`location` presents the location or relative address to write. The location will range from 0 to SAF_BYTES -1.&#160;&#160;&#160; 
Each data Word requires 2 SAF Locations, therefore the location will range from either 0 to 254 or 0 to 126 (in steps of 2),  depending upon the device. 
{empty} +
`data` is the data that is to be read from the SAFM data storage.&#160;&#160;&#160;
A word value.&#160;&#160;&#160;
This must be a variable.
{empty} +
{empty} +
This method reads information to the SAFM given its relative location in the SAFM data storage.&#160;&#160;&#160;
{empty} +
{empty} +
*Example 1:*
----
    '... code preamble to select part
    '... code to setup serial

    'The following example reads the SAFM value into the word variable “data_word_variable” by initially writing some word values.

    dim data_word_variable as word
    SAFWriteWord(  64, 0x1234 )
    SAFWriteWord( 254, 4660 )

    SAFReadWord( 254, data_word_variable )

    HSerPrint "Value = "
    HSerPrint data_word_variable
    HSerPrintCRLF

----
{empty} +
If example 1 where displayed on a serial terminal.&#160;&#160;&#160;The result would show:

----
    Value = 4660
----
{empty} +
{empty} +
*Example 2:*
----
    '... code preamble to select part
    '... code to setup serial

    'The following example reads the SAFM value into the word variable “data_word_variable” by initially writing some word values using a function.

    dim data_word_variable as word
    SAFWriteWord(  64, 0x4321 )
    SAFWriteWord( 254, 17185 )

    data_word_variable = SAFReadWord( 254 )

    HSerPrint "Value = "
    HSerPrint data_word_variable
    HSerPrintCRLF

----
{empty} +
If example 2 where displayed on a serial terminal.&#160;&#160;&#160;The result would show:

----
    Value = 17185
----

{empty} +
{empty} +
See also
<<_safm_overview,SAFM Overview>>,
<<_safread,SAFRead>>,
<<_safreadword,SAFReadWord>>,
<<_safwrite,SAFWrite>>,
<<_safwriteword,SAFWriteWord>>,
<<_safreadblock,SAFReadBlock>>,
<<_safwriteblock,SAFWriteBlock>>,
<<_saferaseblock,SAFEraseBlock>>
