//erv 04110218
==== SAFWriteWord


*Syntax:*
[subs="quotes"]
----
    SAFWriteWord ( location, data_word_value )
----
*Command Availability:*

Available on all PIC micro-controllers with SAFM memory

*Explanation:*
{empty} +
{empty} +
SAFWriteWord is used to write information, word values, to the SAFM data storage, so that it can be accessed later by a programmer on a Personal, or by the SAFRead commands.
{empty} +
{empty} +
`location` presents the location or relative address to write. A data Word requires 2 SAF Locations, therefore the location will range from 0 to 254 in steps of 2. 
{empty} +
{empty} +
`data` is the data that is to be written to the SAFM location.&#160;&#160;&#160;This can be a word value or a word variable.
{empty} +
{empty} +
This method writes information to SAFM given the specific location in SAFM.&#160;&#160;&#160;
This method is similar to the methods for EEPROM, but supports Word values.
{empty} +
{empty} +
*Example 1:*
----
    '... code preamble to select part
    '... code to setup serial

    'The following example stores in the word value of 0x1234 as SAFM location 34
    
    SAFWrite( 0x1234, 34 )
----
{empty} +
{empty} +
*Example 2:*
----
    #chip 18F24K42, 16
    '... code to setup PPS
    '... code to setup serial

    'This example will write two word values to two specific locations.
    
    SAFWriteWord (16, 0xAA01)   'location 16, in this device, equates to 0x7F10
    SAFWriteWord (18, 0xBB02)   'location 18, in this device, equates to 0x7F12
----
{empty} +
{empty} +
If example 2 were displayed on a serial terminal.&#160;&#160;&#160;The result would show, where `--` is the existing value.

----
  Block0  
  7F00    ----  ----  ----  ----  ----  ----  ----  ----
  7F10    AA01  BB02  ----  ----  ----  ----  ----  ---- 
  7F20    ----  ----  ----  ----  ----  ----  ----  ----
  7F30    ----  ----  ----  ----  ----  ----  ----  ----
----
{empty} +
{empty} +
See also
<<_safm_overview,SAFM Overview>>,
<<_safread,SAFRead>>,
<<_safreadword,SAFReadWord>>,
<<_safwrite,SAFWrite>>,
<<_safwriteword,SAFWriteWord>>,
<<_safreadblock,SAFReadBlock>>,
<<_safwriteblock,SAFWriteBlock>>,
<<_saferaseblock,SAFEraseBlock>>
