==== SAFM Overview

*Introduction:*

Some Advanced (18F) and some Enhanced Mid-Range (16F) Microchip PIC devices support Storage Area Flash (SAF) memory. These devices also include EEPROM memory.&#160;&#160;&#160;
SAF memory is not High Endurance, meaning it does not have an endurance of 100K write cyces.&#160;&#160;&#160;
SAF has the same endurance as regular flash memmory, usually specified as 10K write cycles.&#160;&#160;&#160;
{empty} +
{empty} +
SAF memory appears at the top of program memory space and can be used for any purpose, like regular flash program memory.&#160;&#160;&#160; 
Storage Area Flash is intended to be used to store data, such a device calibration data, RF device register settings, and other data. SAFEM can be Read as frequently as necessary.&#160;&#160;&#160; However,  it is not intended to be written frequently like EEPROM. If non-volatile memory need to be written frequenily, it is best to use the EEPROM on these devices.     
{empty} +
{empty} +
As with all flash memory, data must be erased before it can be written and writing this memory will stall the device for a few ms. &#160;&#160;&#160;
Methods to read, write and erase the SAF memory are included in Great Cow BASIC and they are described in this introduction.
{empty} +
{empty} +
The `hefsaf.h` library supports SAF operations for Great Cow BASIC.
{empty} +
{empty} +
Note:  By default, Great Cow BASIC will use SAF memory for regular executable code unless it is told otherwise.&#160;&#160;&#160;
If you wish to store data here, you should reserve the SAF memory by using the compiler option, as shown below to reserve 128 Words of SAF memory:&#160;&#160;&#160;This equates to 256 bytes on PIC 18F microcontrollers and 128 Bytes on PIC 16F microcontrollers 
----
    #option ReserveHighProg 128
----
SAF memory is a block of memory locations found at the top of the Flash program memory.&#160;&#160;&#160;
Each memory location can be used to hold a variable value, either a byte or a word dependent on the specific device.&#160;&#160;&#160;
The main difference between SAF memory and EEPROM is that EEPROM allows byte-by-byte erase whereas the SAF memory does not.&#160;&#160;&#160;
With SAF memory data must be erased before a write and the erase can only be performed in blocks of memory.&#160;&#160;&#160;
The blocks, also called rows, are a fixed size associated with the specific device.&#160;&#160;&#160;
{empty} +
{empty} +
Great Cow BASIC handles the erase operation automatically.&#160;&#160;&#160;
When a write operation is used by a user the Great Cow BASIC library reads to a buffer, update the buffer, erase the block and finally write the buffer back to SAFM.&#160;&#160;&#160;
The complexity of using SAF memory is reduced with the automatically handling of these operations.&#160;&#160;&#160;
{empty} +
{empty} +
The library provides a set of methods to support use of SAF memory.
{empty} +
{empty} +
[cols="2,1,3",width="80%"]
|===
|Method
|Parameters
|Usage

|`SAFWrite`
|a subroutine with the parameters: location, byte value
|SAFWrite ( location, byte_variable )

|`SAFWriteWord`
|a subroutine with the parameters: location, word_value
|SAFWriteWord ( location, word_variable  )

|`SAFRead`
|a function with the parameters: location returns a byte value
|byte_variable = SAFRead ( location  )

|`SAFRead`
|a subroutine with the paramers: location, byte_value
|SAFRead ( location , out_byte_variable )

|`SAFReadWord`
|a function with the parameters: location returns a word value
|word_variable = SAFRead ( location  )

|`SAFReadWord`
|a subroutine with the parameters: location, word_value
|SAFRead ( location , word_variable )

|`SAFEraseBlock`
|a subroutine with the parameters: block_number
|SAFEraseBlock ( 0 )
{empty} +
{empty} +
A value of 0,1,2,3 etc.

|`SAFWriteBlock`
|a subroutine with the parameters: block_number, buffer() [,num_blocks ]
|SAFWriteBlock( 0, myMemoryBuffer ) 'where myMemoryBuffer is an Array or a String
{empty} +
{empty} +
The Array or a String will contain the values to be wrttin to the SAFM.

|`SAFReadBlock`
|a subroutine with the parameters: block_number, buffer() [, num_blocks ]
|SAFReadBlock( 0, myMemoryBuffer ) 'where myMemoryBuffer is an Array or a String.
{empty} +
{empty} +
The Array or a String will contain the values from the SAFM.

|===


{empty} +
{empty} +
The library also defines a set constants that are specific to the device.&#160;&#160;&#160;
These may be useful in the user program.&#160;&#160;&#160;
These constants are used by the library.&#160;&#160;&#160;
A user may use these public constants.
{empty} +
{empty} +
[cols="2,1,3",width="80%"]
|===
|Constant
|Type
|Usage

|`SAF_ROWSIZE_BYTES`
|Byte
|Size of an SAFM block in bytes

|`SAF_WORDS` and `SAF_BYTES`
|Word or a Byte
|ChipSAFMemWords parameter from the device .dat file

|`SAF_START_ADDR`
|Word
|Starting address of SAFM

|`SAF_NUM_BLOCKS`
|Byte
|Number of block of SAFM

|`CHIPWORDS`
|Word
|Device specific constant for the total flash size

|`CHIPSAFMEMWORDS`
|Word
|Device specific constant for the number of SAFM words available

|`CHIPERASEROWSIZEWORDS`
|Word
|Device specific constant for the number of SAFM in an erase row

|===
{empty} +
*Warning*
{empty} +
{empty} +
Whenever you update the hex file of your Microchip PIC micro-controller with your programmer you MAY erase the data that are stored in SAF memory.&#160;&#160;&#160;
If you want to avoid that you will have to flash your Microchip PIC micro-controller with software that allows memory exclusion when flashing.&#160;&#160;&#160;
This is the case with Microchip PIC MPLAB IPE (Go to `Advanced Mode/Enter password/Select Memory/Tick “Preserve Flash on Program”/
Enter Start and End address` of your SAFM).&#160;&#160;&#160;Or, simply use the PICkitPlus suite of software to preserve SAF memory during programming.
{empty} +
{empty} +
See also
<<_safread,SAFRead>>,
<<_safreadword,SAFReadWord>>,
<<_safwrite,SAFWrite>>,
<<_safwriteword,SAFWriteWord>>,
<<_safreadblock,SAFReadBlock>>,
<<_safwriteblock,SAFWriteBlock>>,
<<_saferaseblock,SAFEraseBlock>>
